# ============================================================
# Containerfile: Debian 12 + MariaDB + SSH
# ============================================================

FROM debian:12-slim

ENV DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8

# Fix mirrors
RUN set -eux; \
    if [ -f /etc/apt/sources.list.d/debian.sources ]; then \
      mv /etc/apt/sources.list.d/debian.sources /etc/apt/debian.sources.bak; \
    fi; \
    printf 'deb http://deb.debian.org/debian bookworm main\n' > /etc/apt/sources.list

# Base packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash curl tini \
    openssh-server openssh-client iproute2 netcat-openbsd \
    mariadb-server mariadb-client \
    iputils-ping net-tools && \
    mkdir -p /var/run/sshd && \
    chmod u+s /usr/bin/ping && \
    rm -rf /var/lib/apt/lists/*

# Garantir diretório do MySQL
RUN mkdir -p /var/lib/mysql && chown -R mysql:mysql /var/lib/mysql

# Config MariaDB
RUN sed -ri "s/^(bind-address\s*=).*$/\\1 0.0.0.0/" \
    /etc/mysql/mariadb.conf.d/50-server.cnf || \
    echo -e "[mysqld]\nbind-address=0.0.0.0" \
    > /etc/mysql/mariadb.conf.d/50-server.cnf

# SSH config
RUN sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config \
 && sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config \
 && sed -ri 's@^#?AuthorizedKeysFile .*@AuthorizedKeysFile .ssh/authorized_keys@' /etc/ssh/sshd_config

# Entrypoint
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN sed -i 's/\r$//' /usr/local/bin/docker-entrypoint.sh \
 && chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 22 3306
WORKDIR /app

ENTRYPOINT ["/usr/bin/tini","--","/usr/local/bin/docker-entrypoint.sh"]
CMD ["/usr/sbin/sshd","-D","-e"]
