#!/bin/bash
#run hourly the indexerd daemon

logger "indexerD Info: starting indexerD cron job"

# test if the indexerD.sh script exists and run it
[ -e /usr/local/bin/indexerD.sh ] && . /usr/local/bin/indexerD.sh || {
    logger "indexerD Error: Unable to run indexerD.sh"
    exit 0
}
