/* =====================================================================
   alterProcessingDB-v11-backfill-host-server-metadata.sql
   - Backfill FILE_TASK and FILE_TASK_HISTORY host/server metadata columns
   ===================================================================== */

USE BPDATA;

/*
Initial distribution rule from the legacy single metadata set:

- .bin -> copy to _HOST and _SERVER
- .zip -> copy to _HOST and _SERVER
- .mat -> copy only to _SERVER
*/

UPDATE `FILE_TASK`
SET
  `NA_EXTENSION_HOST` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip') THEN `NA_EXTENSION`
    ELSE `NA_EXTENSION_HOST`
  END,
  `VL_FILE_SIZE_KB_HOST` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip') THEN `VL_FILE_SIZE_KB`
    ELSE `VL_FILE_SIZE_KB_HOST`
  END,
  `DT_FILE_CREATED_HOST` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip') THEN `DT_FILE_CREATED`
    ELSE `DT_FILE_CREATED_HOST`
  END,
  `DT_FILE_MODIFIED_HOST` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip') THEN `DT_FILE_MODIFIED`
    ELSE `DT_FILE_MODIFIED_HOST`
  END,
  `NA_EXTENSION_SERVER` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip', '.mat') THEN `NA_EXTENSION`
    ELSE `NA_EXTENSION_SERVER`
  END,
  `VL_FILE_SIZE_KB_SERVER` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip', '.mat') THEN `VL_FILE_SIZE_KB`
    ELSE `VL_FILE_SIZE_KB_SERVER`
  END,
  `DT_FILE_CREATED_SERVER` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip', '.mat') THEN `DT_FILE_CREATED`
    ELSE `DT_FILE_CREATED_SERVER`
  END,
  `DT_FILE_MODIFIED_SERVER` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip', '.mat') THEN `DT_FILE_MODIFIED`
    ELSE `DT_FILE_MODIFIED_SERVER`
  END
WHERE `NA_EXTENSION` IS NOT NULL;

UPDATE `FILE_TASK_HISTORY`
SET
  `NA_EXTENSION_HOST` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip') THEN `NA_EXTENSION`
    ELSE `NA_EXTENSION_HOST`
  END,
  `VL_FILE_SIZE_KB_HOST` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip') THEN `VL_FILE_SIZE_KB`
    ELSE `VL_FILE_SIZE_KB_HOST`
  END,
  `DT_FILE_CREATED_HOST` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip') THEN `DT_FILE_CREATED`
    ELSE `DT_FILE_CREATED_HOST`
  END,
  `DT_FILE_MODIFIED_HOST` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip') THEN `DT_FILE_MODIFIED`
    ELSE `DT_FILE_MODIFIED_HOST`
  END,
  `NA_EXTENSION_SERVER` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip', '.mat') THEN `NA_EXTENSION`
    ELSE `NA_EXTENSION_SERVER`
  END,
  `VL_FILE_SIZE_KB_SERVER` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip', '.mat') THEN `VL_FILE_SIZE_KB`
    ELSE `VL_FILE_SIZE_KB_SERVER`
  END,
  `DT_FILE_CREATED_SERVER` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip', '.mat') THEN `DT_FILE_CREATED`
    ELSE `DT_FILE_CREATED_SERVER`
  END,
  `DT_FILE_MODIFIED_SERVER` = CASE
    WHEN LOWER(`NA_EXTENSION`) IN ('.bin', '.zip', '.mat') THEN `DT_FILE_MODIFIED`
    ELSE `DT_FILE_MODIFIED_SERVER`
  END
WHERE `NA_EXTENSION` IS NOT NULL;
