USE BPDATA;

ALTER TABLE `FILE_TASK_HISTORY`
  DROP INDEX `idx_fth_dedup_soft`,
  DROP INDEX `idx_fth_host_date`,
  ADD INDEX `idx_fth_host_date_host` (`FK_HOST`, `DT_FILE_CREATED_HOST`),
  DROP COLUMN `NA_EXTENSION`,
  DROP COLUMN `VL_FILE_SIZE_KB`,
  DROP COLUMN `DT_FILE_CREATED`,
  DROP COLUMN `DT_FILE_MODIFIED`;

ALTER TABLE `FILE_TASK`
  DROP COLUMN `NA_EXTENSION`,
  DROP COLUMN `VL_FILE_SIZE_KB`,
  DROP COLUMN `DT_FILE_CREATED`,
  DROP COLUMN `DT_FILE_MODIFIED`;
