/* =====================================================================
   createMeasureDB.sql
   - Canonical RFDATA schema reconciled with the live MariaDB instance
   - Preserves bootstrap LOAD DATA statements for static dimensions
   ===================================================================== */

CREATE DATABASE IF NOT EXISTS RFDATA
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE RFDATA;

CREATE TABLE `DIM_EQUIPMENT_TYPE` (
  `ID_EQUIPMENT_TYPE` int(11) NOT NULL AUTO_INCREMENT,
  `NA_EQUIPMENT_TYPE` varchar(50) DEFAULT NULL,
  `NA_EQUIPMENT_TYPE_UID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_EQUIPMENT_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOAD DATA INFILE '/RFFusion/src/mariadb/scripts/equipmentType.csv'
    INTO TABLE DIM_EQUIPMENT_TYPE
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n'
    IGNORE 1 LINES
    (ID_EQUIPMENT_TYPE, NA_EQUIPMENT_TYPE, NA_EQUIPMENT_TYPE_UID);

CREATE TABLE `DIM_SPECTRUM_EQUIPMENT` (
  `ID_EQUIPMENT` int(11) NOT NULL AUTO_INCREMENT,
  `FK_EQUIPMENT_TYPE` int(11) DEFAULT NULL,
  `NA_EQUIPMENT` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_EQUIPMENT`),
  KEY `FK_EQUIPMENT_TYPE` (`FK_EQUIPMENT_TYPE`),
  FULLTEXT KEY `NA_EQUIPMENT` (`NA_EQUIPMENT`),
  CONSTRAINT `DIM_SPECTRUM_EQUIPMENT_ibfk_1` FOREIGN KEY (`FK_EQUIPMENT_TYPE`) REFERENCES `DIM_EQUIPMENT_TYPE` (`ID_EQUIPMENT_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `DIM_SITE_STATE` (
  `ID_STATE` int(11) NOT NULL,
  `NA_STATE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LC_STATE` varchar(2) DEFAULT NULL,
  PRIMARY KEY (`ID_STATE`),
  FULLTEXT KEY `NA_STATE` (`NA_STATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOAD DATA INFILE '/RFFusion/src/mariadb/scripts/IBGE-BR_UF_2020_BULKLOAD.csv'
    INTO TABLE DIM_SITE_STATE
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n'
    IGNORE 1 LINES
    (ID_STATE, NA_STATE, LC_STATE);

CREATE TABLE `DIM_SITE_COUNTY` (
  `ID_COUNTY` int(11) NOT NULL,
  `FK_STATE` int(11) DEFAULT NULL,
  `NA_COUNTY` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_COUNTY`),
  KEY `FK_STATE` (`FK_STATE`),
  FULLTEXT KEY `NA_COUNTY` (`NA_COUNTY`),
  CONSTRAINT `DIM_SITE_COUNTY_ibfk_1` FOREIGN KEY (`FK_STATE`) REFERENCES `DIM_SITE_STATE` (`ID_STATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOAD DATA INFILE '/RFFusion/src/mariadb/scripts/IBGE-BR_Municipios_2020_BULKLOAD.csv'
    INTO TABLE DIM_SITE_COUNTY
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n'
    IGNORE 1 LINES
    (ID_COUNTY, FK_STATE, @county)
SET NA_COUNTY = TRIM(REPLACE(REPLACE(REPLACE(REPLACE(@county, '|',''), CHAR(13),''), CHAR(10),''), CHAR(9), ''));

UPDATE DIM_SITE_COUNTY
SET NA_COUNTY = TRIM(
        REPLACE(
            REPLACE(
                REPLACE(
                    REPLACE(NA_COUNTY, '|', ''),
                CHAR(13), ''),
            CHAR(10), ''),
        CHAR(9), '')
);

UPDATE DIM_SITE_COUNTY
SET NA_COUNTY = TRIM(NA_COUNTY)
WHERE LENGTH(NA_COUNTY) > 0;

CREATE TABLE `DIM_SITE_DISTRICT` (
  `ID_DISTRICT` int(11) NOT NULL AUTO_INCREMENT,
  `FK_COUNTY` int(11) DEFAULT NULL,
  `NA_DISTRICT` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_DISTRICT`),
  KEY `FK_COUNTY` (`FK_COUNTY`),
  FULLTEXT KEY `NA_DISTRICT` (`NA_DISTRICT`),
  CONSTRAINT `DIM_SITE_DISTRICT_ibfk_1` FOREIGN KEY (`FK_COUNTY`) REFERENCES `DIM_SITE_COUNTY` (`ID_COUNTY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `DIM_SITE_TYPE` (
  `ID_TYPE` int(11) NOT NULL AUTO_INCREMENT,
  `NA_TYPE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `DIM_SPECTRUM_SITE` (
  `ID_SITE` int(11) NOT NULL AUTO_INCREMENT,
  `FK_DISTRICT` int(11) DEFAULT NULL,
  `FK_COUNTY` int(11) DEFAULT NULL,
  `FK_STATE` int(11) DEFAULT NULL,
  `FK_TYPE` int(11) DEFAULT NULL,
  `NA_SITE` varchar(100) DEFAULT NULL,
  `GEO_POINT` point NOT NULL,
  `NU_ALTITUDE` decimal(10,3) DEFAULT NULL,
  `NU_GNSS_MEASUREMENTS` bigint(20) DEFAULT NULL,
  `GEOGRAPHIC_PATH` blob DEFAULT NULL,
  PRIMARY KEY (`ID_SITE`),
  KEY `FK_DISTRICT` (`FK_DISTRICT`),
  KEY `FK_COUNTY` (`FK_COUNTY`),
  KEY `FK_STATE` (`FK_STATE`),
  KEY `FK_TYPE` (`FK_TYPE`),
  SPATIAL KEY `SP_INDEX` (`GEO_POINT`),
  CONSTRAINT `DIM_SPECTRUM_SITE_ibfk_1` FOREIGN KEY (`FK_DISTRICT`) REFERENCES `DIM_SITE_DISTRICT` (`ID_DISTRICT`),
  CONSTRAINT `DIM_SPECTRUM_SITE_ibfk_2` FOREIGN KEY (`FK_COUNTY`) REFERENCES `DIM_SITE_COUNTY` (`ID_COUNTY`),
  CONSTRAINT `DIM_SPECTRUM_SITE_ibfk_3` FOREIGN KEY (`FK_STATE`) REFERENCES `DIM_SITE_STATE` (`ID_STATE`),
  CONSTRAINT `DIM_SPECTRUM_SITE_ibfk_4` FOREIGN KEY (`FK_TYPE`) REFERENCES `DIM_SITE_TYPE` (`ID_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `DIM_FILE_TYPE` (
  `ID_TYPE_FILE` int(11) NOT NULL AUTO_INCREMENT,
  `NA_TYPE_FILE` varchar(50) DEFAULT NULL,
  `NA_EQUIPMENT` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_TYPE_FILE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOAD DATA INFILE '/RFFusion/src/mariadb/scripts/fileType.csv'
    INTO TABLE DIM_FILE_TYPE
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n'
    IGNORE 1 LINES
    (ID_TYPE_FILE, NA_TYPE_FILE, NA_EQUIPMENT);

CREATE TABLE `DIM_SPECTRUM_FILE` (
  `ID_FILE` int(11) NOT NULL AUTO_INCREMENT,
  `DT_FILE_LOGGED` datetime DEFAULT current_timestamp(),
  `ID_TYPE_FILE` int(11) DEFAULT NULL,
  `NA_FILE` varchar(512) DEFAULT NULL,
  `NA_PATH` varchar(3000) DEFAULT NULL,
  `NA_VOLUME` varchar(3000) DEFAULT NULL,
  `NA_EXTENSION` varchar(20) DEFAULT NULL,
  `NU_MD5` varchar(32) DEFAULT NULL,
  `VL_FILE_SIZE_KB` bigint(20) DEFAULT NULL,
  `DT_FILE_CREATED` datetime DEFAULT NULL,
  `DT_FILE_MODIFIED` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_FILE`),
  KEY `ID_TYPE_FILE` (`ID_TYPE_FILE`),
  CONSTRAINT `DIM_SPECTRUM_FILE_ibfk_1` FOREIGN KEY (`ID_TYPE_FILE`) REFERENCES `DIM_FILE_TYPE` (`ID_TYPE_FILE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `DIM_SPECTRUM_DETECTOR` (
  `ID_DETECTOR` int(11) NOT NULL AUTO_INCREMENT,
  `NA_DETECTOR` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_DETECTOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `DIM_SPECTRUM_TRACE_TYPE` (
  `ID_TRACE_TYPE` int(11) NOT NULL AUTO_INCREMENT,
  `NA_TRACE_TYPE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_TRACE_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `DIM_SPECTRUM_UNIT` (
  `ID_MEASURE_UNIT` int(11) NOT NULL AUTO_INCREMENT,
  `NA_MEASURE_UNIT` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID_MEASURE_UNIT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOAD DATA INFILE '/RFFusion/src/mariadb/scripts/measurementUnit.csv'
    INTO TABLE DIM_SPECTRUM_UNIT
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n'
    IGNORE 1 LINES
    (ID_MEASURE_UNIT, NA_MEASURE_UNIT);

CREATE TABLE `DIM_SPECTRUM_EMITTER` (
  `ID_EMITTER` int(11) NOT NULL AUTO_INCREMENT,
  `NA_EMITTER` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_EMITTER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `DIM_SPECTRUM_PROCEDURE` (
  `ID_PROCEDURE` int(11) NOT NULL AUTO_INCREMENT,
  `NA_PROCEDURE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_PROCEDURE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `FACT_SPECTRUM` (
  `ID_SPECTRUM` int(11) NOT NULL AUTO_INCREMENT,
  `FK_SITE` int(11) DEFAULT NULL,
  `FK_DETECTOR` int(11) DEFAULT NULL,
  `FK_TRACE_TYPE` int(11) DEFAULT NULL,
  `FK_MEASURE_UNIT` int(11) DEFAULT NULL,
  `FK_PROCEDURE` int(11) DEFAULT NULL,
  `FK_EQUIPMENT` int(11) DEFAULT NULL,
  `NA_DESCRIPTION` varchar(3000) DEFAULT NULL,
  `NU_FREQ_START` decimal(14,6) DEFAULT NULL,
  `NU_FREQ_END` decimal(14,6) DEFAULT NULL,
  `DT_TIME_START` datetime DEFAULT NULL,
  `DT_TIME_END` datetime DEFAULT NULL,
  `NU_SAMPLE_DURATION` decimal(9,3) DEFAULT NULL,
  `NU_TRACE_COUNT` int(11) DEFAULT NULL,
  `NU_TRACE_LENGTH` int(11) DEFAULT NULL,
  `NU_RBW` decimal(12,1) DEFAULT NULL,
  `NU_VBW` decimal(12,1) DEFAULT NULL,
  `NU_ATT_GAIN` decimal(4,1) DEFAULT NULL,
  `JS_METADATA` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Additional spectrum metadata (non-dimensional)' CHECK (json_valid(`JS_METADATA`)),
  PRIMARY KEY (`ID_SPECTRUM`),
  KEY `FK_SITE` (`FK_SITE`),
  KEY `FK_DETECTOR` (`FK_DETECTOR`),
  KEY `FK_TRACE_TYPE` (`FK_TRACE_TYPE`),
  KEY `FK_MEASURE_UNIT` (`FK_MEASURE_UNIT`),
  KEY `FK_PROCEDURE` (`FK_PROCEDURE`),
  KEY `FK_EQUIPMENT` (`FK_EQUIPMENT`),
  KEY `IX_FACT_SPECTRUM_IDEMPOTENCY` (`FK_SITE`,`FK_EQUIPMENT`,`FK_PROCEDURE`,`FK_TRACE_TYPE`,`NU_FREQ_START`,`NU_FREQ_END`,`DT_TIME_START`,`NU_TRACE_LENGTH`),
  KEY `IX_FACT_SPECTRUM_WEBFUSION_SEARCH` (`FK_EQUIPMENT`,`DT_TIME_END`,`DT_TIME_START`,`ID_SPECTRUM`),
  CONSTRAINT `FACT_SPECTRUM_ibfk_1` FOREIGN KEY (`FK_SITE`) REFERENCES `DIM_SPECTRUM_SITE` (`ID_SITE`),
  CONSTRAINT `FACT_SPECTRUM_ibfk_2` FOREIGN KEY (`FK_DETECTOR`) REFERENCES `DIM_SPECTRUM_DETECTOR` (`ID_DETECTOR`),
  CONSTRAINT `FACT_SPECTRUM_ibfk_3` FOREIGN KEY (`FK_TRACE_TYPE`) REFERENCES `DIM_SPECTRUM_TRACE_TYPE` (`ID_TRACE_TYPE`),
  CONSTRAINT `FACT_SPECTRUM_ibfk_4` FOREIGN KEY (`FK_MEASURE_UNIT`) REFERENCES `DIM_SPECTRUM_UNIT` (`ID_MEASURE_UNIT`),
  CONSTRAINT `FACT_SPECTRUM_ibfk_5` FOREIGN KEY (`FK_PROCEDURE`) REFERENCES `DIM_SPECTRUM_PROCEDURE` (`ID_PROCEDURE`),
  CONSTRAINT `FACT_SPECTRUM_ibfk_6` FOREIGN KEY (`FK_EQUIPMENT`) REFERENCES `DIM_SPECTRUM_EQUIPMENT` (`ID_EQUIPMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `BRIDGE_SPECTRUM_EMITTER` (
  `FK_EMITTER` int(11) NOT NULL,
  `FK_SPECTRUM` int(11) NOT NULL,
  PRIMARY KEY (`FK_EMITTER`,`FK_SPECTRUM`),
  KEY `FK_SPECTRUM` (`FK_SPECTRUM`),
  CONSTRAINT `BRIDGE_SPECTRUM_EMITTER_ibfk_1` FOREIGN KEY (`FK_EMITTER`) REFERENCES `DIM_SPECTRUM_EMITTER` (`ID_EMITTER`),
  CONSTRAINT `BRIDGE_SPECTRUM_EMITTER_ibfk_2` FOREIGN KEY (`FK_SPECTRUM`) REFERENCES `FACT_SPECTRUM` (`ID_SPECTRUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `BRIDGE_SPECTRUM_FILE` (
  `FK_FILE` int(11) NOT NULL,
  `FK_SPECTRUM` int(11) NOT NULL,
  PRIMARY KEY (`FK_FILE`,`FK_SPECTRUM`),
  KEY `IX_BRIDGE_SPECTRUM_FILE_SPECTRUM` (`FK_SPECTRUM`,`FK_FILE`),
  CONSTRAINT `BRIDGE_SPECTRUM_FILE_ibfk_1` FOREIGN KEY (`FK_FILE`) REFERENCES `DIM_SPECTRUM_FILE` (`ID_FILE`),
  CONSTRAINT `BRIDGE_SPECTRUM_FILE_ibfk_2` FOREIGN KEY (`FK_SPECTRUM`) REFERENCES `FACT_SPECTRUM` (`ID_SPECTRUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
