/* =====================================================================
   createFusionSummaryDB.sql
   Canonical RFFUSION_SUMMARY schema — current as of schema v3.

   Changelog
   ---------
   v1 — initial schema reconciled with the live MariaDB instance.
   v2 — geography keys (FK_COUNTY, FK_DISTRICT) promoted into
        SITE_EQUIPMENT_OBS_SUMMARY, HOST_LOCATION_SUMMARY and
        MAP_SITE_SUMMARY so features such as /spectrum, map payloads
        and host locality history can resolve district/county without
        joining back to live RFDATA dimension tables.
        (Previously delivered as alterFusionSummaryDB-v2-geography-keys.sql)
   v3 — current-month backup throughput by `DT_BACKUP` materialized into
        HOST_CURRENT_SNAPSHOT and aggregated into SERVER_CURRENT_SUMMARY via
        `NU_BACKUP_DONE_THIS_MONTH` and `VL_BACKUP_DONE_GB_THIS_MONTH`.
        This script is now the canonical source for that schema state; the
        transitional alter script is retired.
   v4 — `SUMMARY_OUTBOX` simplified into one pending row per dirty scope.
        The public runtime no longer depends on opaque JSON payloads or an
        append-only event log to drive incremental refresh.

   Note on shadow tables
   ---------------------
   The summary worker uses an atomic-swap pattern (CREATE … SELECT, then
   RENAME TABLE) for heavy refreshes. The *_shadow tables it creates at
   runtime are transient and are therefore NOT defined here; the worker
   is responsible for their lifecycle.
   ===================================================================== */

CREATE DATABASE IF NOT EXISTS RFFUSION_SUMMARY
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE RFFUSION_SUMMARY;

CREATE TABLE `SUMMARY_REFRESH_LOG` (
  `ID_REFRESH_LOG` bigint(20) NOT NULL AUTO_INCREMENT,
  `NA_OBJECT_NAME` varchar(100) NOT NULL,
  `DT_STARTED_AT` datetime NOT NULL,
  `DT_FINISHED_AT` datetime DEFAULT NULL,
  `IS_SUCCESS` tinyint(1) NOT NULL DEFAULT 0,
  `NU_ROW_COUNT` bigint(20) DEFAULT NULL,
  `NA_SOURCE_HIGH_WATERMARK` varchar(255) DEFAULT NULL,
  `NA_ERROR_MESSAGE` text DEFAULT NULL,
  PRIMARY KEY (`ID_REFRESH_LOG`),
  KEY `IX_SUMMARY_REFRESH_LOG_OBJECT` (`NA_OBJECT_NAME`,`DT_STARTED_AT` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `SUMMARY_OUTBOX` (
  `ID_OUTBOX` bigint(20) NOT NULL AUTO_INCREMENT,
  `NA_SCOPE_TYPE` varchar(32) NOT NULL,
  `NA_SCOPE_VALUE` varchar(64) NOT NULL,
  `NA_SOURCE_HANDLER` varchar(64) DEFAULT NULL,
  `NA_REASON` varchar(64) DEFAULT NULL,
  `DT_CREATED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID_OUTBOX`),
  UNIQUE KEY `UQ_SUMMARY_OUTBOX_SCOPE` (`NA_SCOPE_TYPE`,`NA_SCOPE_VALUE`),
  KEY `IX_SUMMARY_OUTBOX_CREATED` (`DT_CREATED_AT`,`ID_OUTBOX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `SUMMARY_WORKER_STATE` (
  `NA_CONSUMER` varchar(64) NOT NULL,
  `ID_LAST_OUTBOX` bigint(20) NOT NULL DEFAULT 0,
  `DT_LAST_START` datetime DEFAULT NULL,
  `DT_LAST_END` datetime DEFAULT NULL,
  `DT_LAST_SUCCESS` datetime DEFAULT NULL,
  `DT_LAST_FAILURE` datetime DEFAULT NULL,
  `NU_LAST_BATCH_SIZE` int(11) NOT NULL DEFAULT 0,
  `NU_LAST_EVENT_COUNT` int(11) NOT NULL DEFAULT 0,
  `NA_STATUS` varchar(32) NOT NULL DEFAULT 'idle',
  `NA_ERROR_MESSAGE` text DEFAULT NULL,
  PRIMARY KEY (`NA_CONSUMER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_EQUIPMENT_LINK_OVERRIDE` (
  `ID_OVERRIDE` bigint(20) NOT NULL AUTO_INCREMENT,
  `FK_HOST` int(11) NOT NULL,
  `FK_EQUIPMENT` int(11) NOT NULL,
  `NA_OVERRIDE_REASON` varchar(255) DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT 1,
  `DT_CREATED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  `DT_UPDATED_AT` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID_OVERRIDE`),
  UNIQUE KEY `UQ_HOST_EQUIPMENT_LINK_OVERRIDE` (`FK_HOST`,`FK_EQUIPMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_EQUIPMENT_LINK` (
  `ID_LINK` bigint(20) NOT NULL AUTO_INCREMENT,
  `FK_HOST` int(11) NOT NULL,
  `FK_EQUIPMENT` int(11) NOT NULL,
  `NA_EQUIPMENT` varchar(100) NOT NULL,
  `NA_MATCH_TYPE` varchar(32) NOT NULL,
  `VL_MATCH_CONFIDENCE` decimal(5,2) NOT NULL DEFAULT 0.00,
  `IS_PRIMARY_LINK` tinyint(1) NOT NULL DEFAULT 0,
  `IS_MANUAL_OVERRIDE` tinyint(1) NOT NULL DEFAULT 0,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_LINK`),
  UNIQUE KEY `UQ_HOST_EQUIPMENT_LINK` (`FK_HOST`,`FK_EQUIPMENT`),
  KEY `IX_HOST_EQUIPMENT_LINK_HOST` (`FK_HOST`,`IS_ACTIVE`,`IS_PRIMARY_LINK`),
  KEY `IX_HOST_EQUIPMENT_LINK_EQUIPMENT` (`FK_EQUIPMENT`,`IS_ACTIVE`,`IS_PRIMARY_LINK`),
  KEY `IX_HOST_EQUIPMENT_LINK_MATCH` (`NA_MATCH_TYPE`,`VL_MATCH_CONFIDENCE` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `SITE_EQUIPMENT_OBS_SUMMARY` (
  `FK_SITE` int(11) NOT NULL,
  `FK_EQUIPMENT` int(11) NOT NULL,
  `NA_SITE_NAME` varchar(100) DEFAULT NULL,
  `NA_SITE_LABEL` varchar(120) NOT NULL,
  `FK_COUNTY` int(11) DEFAULT NULL,
  `FK_DISTRICT` int(11) DEFAULT NULL,
  `NA_COUNTY_NAME` varchar(150) DEFAULT NULL,
  `NA_DISTRICT_NAME` varchar(100) DEFAULT NULL,
  `ID_STATE` int(11) DEFAULT NULL,
  `NA_STATE_NAME` varchar(100) DEFAULT NULL,
  `NA_STATE_CODE` varchar(2) DEFAULT NULL,
  `VL_LATITUDE` decimal(10,7) DEFAULT NULL,
  `VL_LONGITUDE` decimal(10,7) DEFAULT NULL,
  `VL_ALTITUDE` decimal(10,3) DEFAULT NULL,
  `NU_GNSS_MEASUREMENTS` bigint(20) DEFAULT NULL,
  `NA_EQUIPMENT` varchar(100) DEFAULT NULL,
  `DT_FIRST_SEEN_AT` datetime DEFAULT NULL,
  `DT_LAST_SEEN_AT` datetime DEFAULT NULL,
  `NU_SPECTRUM_COUNT` bigint(20) NOT NULL DEFAULT 0,
  `ID_LAST_SPECTRUM` bigint(20) DEFAULT NULL,
  `IS_CURRENT_LOCATION` tinyint(1) NOT NULL DEFAULT 0,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`FK_SITE`,`FK_EQUIPMENT`),
  KEY `IX_SITE_EQUIPMENT_OBS_EQUIPMENT` (`FK_EQUIPMENT`,`IS_CURRENT_LOCATION`,`DT_LAST_SEEN_AT`),
  KEY `IX_SITE_EQUIPMENT_OBS_SITE` (`FK_SITE`,`DT_LAST_SEEN_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_LOCATION_SUMMARY` (
  `FK_HOST` int(11) NOT NULL,
  `FK_SITE` int(11) NOT NULL,
  `NA_HOST_NAME` varchar(100) NOT NULL,
  `NA_LOCALITY_LABEL` varchar(255) NOT NULL,
  `NA_SITE_LABEL` varchar(120) NOT NULL,
  `FK_COUNTY` int(11) DEFAULT NULL,
  `FK_DISTRICT` int(11) DEFAULT NULL,
  `NA_COUNTY_NAME` varchar(150) DEFAULT NULL,
  `NA_DISTRICT_NAME` varchar(100) DEFAULT NULL,
  `ID_STATE` int(11) DEFAULT NULL,
  `NA_STATE_NAME` varchar(100) DEFAULT NULL,
  `NA_STATE_CODE` varchar(2) DEFAULT NULL,
  `VL_LATITUDE` decimal(10,7) DEFAULT NULL,
  `VL_LONGITUDE` decimal(10,7) DEFAULT NULL,
  `VL_ALTITUDE` decimal(10,3) DEFAULT NULL,
  `DT_FIRST_SEEN_AT` datetime DEFAULT NULL,
  `DT_LAST_SEEN_AT` datetime DEFAULT NULL,
  `NU_SPECTRUM_COUNT` bigint(20) NOT NULL DEFAULT 0,
  `NU_MATCHED_EQUIPMENT_TOTAL` int(11) NOT NULL DEFAULT 0,
  `IS_CURRENT_LOCATION` tinyint(1) NOT NULL DEFAULT 0,
  `IS_OFFLINE_SNAPSHOT` tinyint(1) NOT NULL DEFAULT 0,
  `VL_MAX_MATCH_CONFIDENCE` decimal(5,2) DEFAULT NULL,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`FK_HOST`,`FK_SITE`),
  KEY `IX_HOST_LOCATION_CURRENT` (`FK_HOST`,`IS_CURRENT_LOCATION`,`DT_LAST_SEEN_AT`),
  KEY `IX_HOST_LOCATION_SITE` (`FK_SITE`,`DT_LAST_SEEN_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `MAP_SITE_STATION_SUMMARY` (
  `FK_SITE` int(11) NOT NULL,
  `FK_EQUIPMENT` int(11) NOT NULL,
  `FK_HOST` int(11) DEFAULT NULL,
  `NA_SITE_LABEL` varchar(120) NOT NULL,
  `NA_EQUIPMENT` varchar(100) DEFAULT NULL,
  `NA_HOST_NAME` varchar(100) DEFAULT NULL,
  `IS_OFFLINE` tinyint(1) DEFAULT NULL,
  `IS_CURRENT_LOCATION` tinyint(1) NOT NULL DEFAULT 0,
  `NA_MAP_STATE` varchar(32) NOT NULL,
  `NU_STATE_PRIORITY` smallint(6) NOT NULL DEFAULT 4,
  `DT_FIRST_SEEN_AT` datetime DEFAULT NULL,
  `DT_LAST_SEEN_AT` datetime DEFAULT NULL,
  `NU_SPECTRUM_COUNT` bigint(20) NOT NULL DEFAULT 0,
  `NA_MATCH_TYPE` varchar(32) DEFAULT NULL,
  `VL_MATCH_CONFIDENCE` decimal(5,2) DEFAULT NULL,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`FK_SITE`,`FK_EQUIPMENT`),
  KEY `IX_MAP_SITE_STATION_SITE` (`FK_SITE`,`NU_STATE_PRIORITY`,`NA_HOST_NAME`),
  KEY `IX_MAP_SITE_STATION_HOST` (`FK_HOST`,`NA_MAP_STATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `MAP_SITE_SUMMARY` (
  `FK_SITE` int(11) NOT NULL,
  `NA_SITE_LABEL` varchar(120) NOT NULL,
  `FK_COUNTY` int(11) DEFAULT NULL,
  `FK_DISTRICT` int(11) DEFAULT NULL,
  `NA_COUNTY_NAME` varchar(150) DEFAULT NULL,
  `NA_DISTRICT_NAME` varchar(100) DEFAULT NULL,
  `ID_STATE` int(11) DEFAULT NULL,
  `NA_STATE_NAME` varchar(100) DEFAULT NULL,
  `NA_STATE_CODE` varchar(2) DEFAULT NULL,
  `VL_LATITUDE` decimal(10,7) DEFAULT NULL,
  `VL_LONGITUDE` decimal(10,7) DEFAULT NULL,
  `VL_ALTITUDE` decimal(10,3) DEFAULT NULL,
  `NU_GNSS_MEASUREMENTS` bigint(20) DEFAULT NULL,
  `NA_MARKER_STATE` varchar(32) NOT NULL DEFAULT 'no_host',
  `NU_STATION_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_KNOWN_HOST_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_ONLINE_CURRENT_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_ONLINE_PREVIOUS_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_OFFLINE_CURRENT_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_OFFLINE_PREVIOUS_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_NO_HOST_COUNT` int(11) NOT NULL DEFAULT 0,
  `HAS_ONLINE_STATION` tinyint(1) NOT NULL DEFAULT 0,
  `HAS_ONLINE_HOST` tinyint(1) NOT NULL DEFAULT 0,
  `HAS_KNOWN_HOST` tinyint(1) NOT NULL DEFAULT 0,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`FK_SITE`),
  KEY `IX_MAP_SITE_SUMMARY_STATE` (`NA_MARKER_STATE`,`NA_STATE_CODE`),
  KEY `IX_MAP_SITE_SUMMARY_LOCATION` (`NA_COUNTY_NAME`,`NA_STATE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_MONTHLY_METRIC` (
  `FK_HOST` int(11) NOT NULL,
  `DT_REFERENCE_MONTH` date NOT NULL,
  `NU_DISCOVERED_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_DISCOVERED_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_BACKUP_DONE_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_BACKUP_DONE_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_BACKUP_PENDING_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_BACKUP_PENDING_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_BACKUP_ERROR_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_BACKUP_ERROR_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_PROCESSING_DONE_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_PROCESSING_DONE_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_PROCESSING_PENDING_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_PROCESSING_PENDING_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_PROCESSING_ERROR_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_PROCESSING_ERROR_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`FK_HOST`,`DT_REFERENCE_MONTH`),
  KEY `IX_HOST_MONTHLY_METRIC_MONTH` (`DT_REFERENCE_MONTH`,`FK_HOST`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_ERROR_SUMMARY` (
  `ID_HOST_ERROR_SUMMARY` bigint(20) NOT NULL AUTO_INCREMENT,
  `FK_HOST` int(11) NOT NULL,
  `NA_ERROR_SCOPE` varchar(32) NOT NULL,
  `NA_ERROR_DOMAIN` varchar(32) DEFAULT NULL,
  `NA_ERROR_STAGE` varchar(32) DEFAULT NULL,
  `NA_ERROR_CODE` varchar(64) DEFAULT NULL,
  `NA_ERROR_SUMMARY_HASH` char(64) NOT NULL,
  `NA_ERROR_SUMMARY` text DEFAULT NULL,
  `NU_ERROR_COUNT` bigint(20) NOT NULL DEFAULT 0,
  `DT_LAST_SEEN_AT` datetime DEFAULT NULL,
  `ID_LAST_SOURCE_ROW` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID_HOST_ERROR_SUMMARY`),
  UNIQUE KEY `UQ_HOST_ERROR_SUMMARY` (`FK_HOST`,`NA_ERROR_SCOPE`,`NA_ERROR_DOMAIN`,`NA_ERROR_STAGE`,`NA_ERROR_CODE`,`NA_ERROR_SUMMARY_HASH`),
  KEY `IX_HOST_ERROR_SUMMARY_HOST` (`FK_HOST`,`NA_ERROR_SCOPE`,`NU_ERROR_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `SERVER_ERROR_SUMMARY` (
  `ID_SERVER_ERROR_SUMMARY` bigint(20) NOT NULL AUTO_INCREMENT,
  `NA_ERROR_SCOPE` varchar(32) NOT NULL,
  `NA_ERROR_DOMAIN` varchar(32) DEFAULT NULL,
  `NA_ERROR_STAGE` varchar(32) DEFAULT NULL,
  `NA_ERROR_CODE` varchar(64) DEFAULT NULL,
  `NA_ERROR_SUMMARY_HASH` char(64) NOT NULL,
  `NA_ERROR_SUMMARY` text DEFAULT NULL,
  `NU_ERROR_COUNT` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID_SERVER_ERROR_SUMMARY`),
  UNIQUE KEY `UQ_SERVER_ERROR_SUMMARY` (`NA_ERROR_SCOPE`,`NA_ERROR_DOMAIN`,`NA_ERROR_STAGE`,`NA_ERROR_CODE`,`NA_ERROR_SUMMARY_HASH`),
  KEY `IX_SERVER_ERROR_SUMMARY_SCOPE` (`NA_ERROR_SCOPE`,`NU_ERROR_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_CURRENT_SNAPSHOT` (
  `ID_HOST` int(11) NOT NULL,
  `NA_HOST_NAME` varchar(100) NOT NULL,
  `NA_HOST_ADDRESS` varchar(50) DEFAULT NULL,
  `NA_HOST_PORT` int(11) DEFAULT NULL,
  `IS_OFFLINE` tinyint(1) NOT NULL DEFAULT 0,
  `IS_BUSY` tinyint(1) NOT NULL DEFAULT 0,
  `NU_PID` int(11) DEFAULT NULL,
  `DT_BUSY` datetime DEFAULT NULL,
  `DT_LAST_FAIL` datetime DEFAULT NULL,
  `DT_LAST_CHECK` datetime DEFAULT NULL,
  `NU_HOST_CHECK_ERROR` int(11) DEFAULT NULL,
  `DT_LAST_DISCOVERY` datetime DEFAULT NULL,
  `DT_LAST_BACKUP` datetime DEFAULT NULL,
  `NU_PENDING_FILE_BACKUP_TASKS` int(11) DEFAULT NULL,
  `NU_ERROR_FILE_BACKUP_TASKS` int(11) DEFAULT NULL,
  `NU_BACKUP_DONE_THIS_MONTH` int(11) NOT NULL DEFAULT 0,
  `VL_PENDING_BACKUP_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `VL_BACKUP_DONE_GB_THIS_MONTH` decimal(18,2) NOT NULL DEFAULT 0.00,
  `VL_DONE_BACKUP_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `DT_LAST_PROCESSING` datetime DEFAULT NULL,
  `NU_PENDING_FILE_PROCESS_TASKS` int(11) DEFAULT NULL,
  `NU_ERROR_FILE_PROCESS_TASKS` int(11) DEFAULT NULL,
  `NU_HOST_FILES` int(11) DEFAULT NULL,
  `NU_BACKUP_QUEUE_FILES_TOTAL` int(11) NOT NULL DEFAULT 0,
  `VL_BACKUP_QUEUE_GB_TOTAL` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_PROCESSING_QUEUE_FILES_TOTAL` int(11) NOT NULL DEFAULT 0,
  `VL_PROCESSING_QUEUE_GB_TOTAL` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_MATCHED_EQUIPMENT_TOTAL` int(11) NOT NULL DEFAULT 0,
  `NU_FACT_SPECTRUM_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NA_CURRENT_SITE_LABEL` varchar(120) DEFAULT NULL,
  `NA_CURRENT_STATE_CODE` varchar(2) DEFAULT NULL,
  `NA_LAST_ERROR_CODE` varchar(64) DEFAULT NULL,
  `NA_LAST_ERROR_SUMMARY` text DEFAULT NULL,
  `DT_LAST_ERROR_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_HOST`),
  KEY `IX_HOST_CURRENT_SNAPSHOT_STATUS` (`IS_OFFLINE`,`IS_BUSY`,`NA_HOST_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `SERVER_CURRENT_SUMMARY` (
  `ID_SUMMARY` tinyint(4) NOT NULL,
  `NA_CURRENT_MONTH_LABEL` char(7) NOT NULL,
  `NU_TOTAL_HOSTS` int(11) NOT NULL DEFAULT 0,
  `NU_ONLINE_HOSTS` int(11) NOT NULL DEFAULT 0,
  `NU_OFFLINE_HOSTS` int(11) NOT NULL DEFAULT 0,
  `NU_BUSY_HOSTS` int(11) NOT NULL DEFAULT 0,
  `NU_DISCOVERED_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_BACKUP_PENDING_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `VL_BACKUP_PENDING_GB_TOTAL` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_BACKUP_ERROR_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_BACKUP_QUEUE_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `VL_BACKUP_QUEUE_GB_TOTAL` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_PROCESSING_PENDING_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_PROCESSING_DONE_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_PROCESSING_ERROR_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_PROCESSING_QUEUE_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `VL_PROCESSING_QUEUE_GB_TOTAL` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_FACT_SPECTRUM_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_BACKUP_DONE_THIS_MONTH` bigint(20) NOT NULL DEFAULT 0,
  `VL_BACKUP_DONE_GB_THIS_MONTH` decimal(18,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`ID_SUMMARY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `WEBFUSION_USAGE_METRIC_MONTHLY` (
  `NA_METRIC_NAME` varchar(64) NOT NULL,
  `DT_REFERENCE_MONTH` date NOT NULL,
  `NU_VALUE` bigint(20) NOT NULL DEFAULT 0,
  `DT_UPDATED_AT` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`NA_METRIC_NAME`,`DT_REFERENCE_MONTH`),
  KEY `IX_WEBFUSION_USAGE_MONTH` (`DT_REFERENCE_MONTH`,`NA_METRIC_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `WEBFUSION_USAGE_LOG_CHECKPOINT` (
  `NA_SOURCE_NAME` varchar(64) NOT NULL,
  `NA_LOG_PATH` varchar(255) NOT NULL,
  `NA_FILE_SIGNATURE` varchar(128) DEFAULT NULL,
  `NU_LAST_OFFSET` bigint(20) NOT NULL DEFAULT 0,
  `NU_LAST_SIZE` bigint(20) NOT NULL DEFAULT 0,
  `NU_LAST_MTIME_NS` bigint(20) NOT NULL DEFAULT 0,
  `DT_UPDATED_AT` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`NA_SOURCE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET @wf_old_usage_table_exists := (
    SELECT COUNT(*)
    FROM information_schema.tables
    WHERE table_schema = 'RFFUSION_SUMMARY'
      AND table_name = 'WEBFUSION_USAGE_METRIC'
);

SET @wf_usage_migration_sql := IF(
    @wf_old_usage_table_exists > 0,
    '
    INSERT INTO `WEBFUSION_USAGE_METRIC_MONTHLY`
        (`NA_METRIC_NAME`, `DT_REFERENCE_MONTH`, `NU_VALUE`)
    SELECT
        `NA_METRIC_NAME`,
        DATE_FORMAT(CURDATE(), ''%Y-%m-01''),
        `NU_VALUE`
    FROM `WEBFUSION_USAGE_METRIC`
    WHERE `NU_VALUE` <> 0
    ON DUPLICATE KEY UPDATE
        `NU_VALUE` = GREATEST(VALUES(`NU_VALUE`), `NU_VALUE`)
    ',
    'DO 0'
);

PREPARE wf_usage_migration_stmt FROM @wf_usage_migration_sql;
EXECUTE wf_usage_migration_stmt;
DEALLOCATE PREPARE wf_usage_migration_stmt;

CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `RFFUSION_SUMMARY`.`VW_ERROR_EVENT_CANONICAL` AS select 'FILE_TASK_HISTORY' AS `NA_SOURCE_TABLE`,`f`.`ID_HISTORY` AS `ID_SOURCE_ROW`,'BACKUP' AS `NA_ERROR_SCOPE`,`f`.`FK_HOST` AS `FK_HOST`,`h`.`NA_HOST_NAME` AS `NA_HOST_NAME`,coalesce(`f`.`DT_BACKUP`,`f`.`DT_DISCOVERED`,`f`.`DT_FILE_CREATED`,`f`.`DT_FILE_MODIFIED`) AS `DT_EVENT_AT`,`f`.`NU_STATUS_BACKUP` AS `NU_STATUS_VALUE`,nullif(trim(`f`.`NA_ERROR_DOMAIN`),'') AS `NA_ERROR_DOMAIN`,nullif(trim(`f`.`NA_ERROR_STAGE`),'') AS `NA_ERROR_STAGE`,nullif(trim(`f`.`NA_ERROR_CODE`),'') AS `NA_ERROR_CODE`,coalesce(nullif(trim(`f`.`NA_ERROR_SUMMARY`),''),nullif(trim(`f`.`NA_MESSAGE`),''),'(Sem mensagem)') AS `NA_ERROR_SUMMARY`,sha2(coalesce(nullif(trim(`f`.`NA_ERROR_SUMMARY`),''),nullif(trim(`f`.`NA_MESSAGE`),''),'(Sem mensagem)'),256) AS `NA_ERROR_SUMMARY_HASH`,`f`.`NA_ERROR_DETAIL` AS `NA_ERROR_DETAIL`,`f`.`NU_ERROR_CLASSIFIER_VERSION` AS `NU_ERROR_CLASSIFIER_VERSION`,`f`.`NA_MESSAGE` AS `NA_RAW_MESSAGE` from (`BPDATA`.`FILE_TASK_HISTORY` `f` left join `BPDATA`.`HOST` `h` on(`h`.`ID_HOST` = `f`.`FK_HOST`)) where `f`.`NU_STATUS_BACKUP` = -1 union all select 'FILE_TASK_HISTORY' AS `NA_SOURCE_TABLE`,`f`.`ID_HISTORY` AS `ID_SOURCE_ROW`,'PROCESSING' AS `NA_ERROR_SCOPE`,`f`.`FK_HOST` AS `FK_HOST`,`h`.`NA_HOST_NAME` AS `NA_HOST_NAME`,coalesce(`f`.`DT_PROCESSED`,`f`.`DT_BACKUP`,`f`.`DT_DISCOVERED`,`f`.`DT_FILE_CREATED`,`f`.`DT_FILE_MODIFIED`) AS `DT_EVENT_AT`,`f`.`NU_STATUS_PROCESSING` AS `NU_STATUS_VALUE`,nullif(trim(`f`.`NA_ERROR_DOMAIN`),'') AS `NA_ERROR_DOMAIN`,nullif(trim(`f`.`NA_ERROR_STAGE`),'') AS `NA_ERROR_STAGE`,nullif(trim(`f`.`NA_ERROR_CODE`),'') AS `NA_ERROR_CODE`,coalesce(nullif(trim(`f`.`NA_ERROR_SUMMARY`),''),nullif(trim(`f`.`NA_MESSAGE`),''),'(Sem mensagem)') AS `NA_ERROR_SUMMARY`,sha2(coalesce(nullif(trim(`f`.`NA_ERROR_SUMMARY`),''),nullif(trim(`f`.`NA_MESSAGE`),''),'(Sem mensagem)'),256) AS `NA_ERROR_SUMMARY_HASH`,`f`.`NA_ERROR_DETAIL` AS `NA_ERROR_DETAIL`,`f`.`NU_ERROR_CLASSIFIER_VERSION` AS `NU_ERROR_CLASSIFIER_VERSION`,`f`.`NA_MESSAGE` AS `NA_RAW_MESSAGE` from (`BPDATA`.`FILE_TASK_HISTORY` `f` left join `BPDATA`.`HOST` `h` on(`h`.`ID_HOST` = `f`.`FK_HOST`)) where `f`.`NU_STATUS_PROCESSING` = -1 union all select 'FILE_TASK' AS `NA_SOURCE_TABLE`,`t`.`ID_FILE_TASK` AS `ID_SOURCE_ROW`,case when `t`.`NU_TYPE` = 1 then 'BACKUP_QUEUE' when `t`.`NU_TYPE` = 2 then 'PROCESSING_QUEUE' else 'FILE_TASK' end AS `NA_ERROR_SCOPE`,`t`.`FK_HOST` AS `FK_HOST`,`h`.`NA_HOST_NAME` AS `NA_HOST_NAME`,coalesce(`t`.`DT_FILE_TASK`,`t`.`DT_FILE_CREATED`,`t`.`DT_FILE_MODIFIED`) AS `DT_EVENT_AT`,`t`.`NU_STATUS` AS `NU_STATUS_VALUE`,nullif(trim(`t`.`NA_ERROR_DOMAIN`),'') AS `NA_ERROR_DOMAIN`,nullif(trim(`t`.`NA_ERROR_STAGE`),'') AS `NA_ERROR_STAGE`,nullif(trim(`t`.`NA_ERROR_CODE`),'') AS `NA_ERROR_CODE`,coalesce(nullif(trim(`t`.`NA_ERROR_SUMMARY`),''),nullif(trim(`t`.`NA_MESSAGE`),''),'(Sem mensagem)') AS `NA_ERROR_SUMMARY`,sha2(coalesce(nullif(trim(`t`.`NA_ERROR_SUMMARY`),''),nullif(trim(`t`.`NA_MESSAGE`),''),'(Sem mensagem)'),256) AS `NA_ERROR_SUMMARY_HASH`,`t`.`NA_ERROR_DETAIL` AS `NA_ERROR_DETAIL`,`t`.`NU_ERROR_CLASSIFIER_VERSION` AS `NU_ERROR_CLASSIFIER_VERSION`,`t`.`NA_MESSAGE` AS `NA_RAW_MESSAGE` from (`BPDATA`.`FILE_TASK` `t` left join `BPDATA`.`HOST` `h` on(`h`.`ID_HOST` = `t`.`FK_HOST`)) where `t`.`NU_STATUS` = -1 union all select 'HOST_TASK' AS `NA_SOURCE_TABLE`,`ht`.`ID_HOST_TASK` AS `ID_SOURCE_ROW`,'HOST_TASK' AS `NA_ERROR_SCOPE`,`ht`.`FK_HOST` AS `FK_HOST`,`h`.`NA_HOST_NAME` AS `NA_HOST_NAME`,`ht`.`DT_HOST_TASK` AS `DT_EVENT_AT`,`ht`.`NU_STATUS` AS `NU_STATUS_VALUE`,NULL AS `NA_ERROR_DOMAIN`,NULL AS `NA_ERROR_STAGE`,NULL AS `NA_ERROR_CODE`,coalesce(nullif(trim(`ht`.`NA_MESSAGE`),''),'(Sem mensagem)') AS `NA_ERROR_SUMMARY`,sha2(coalesce(nullif(trim(`ht`.`NA_MESSAGE`),''),'(Sem mensagem)'),256) AS `NA_ERROR_SUMMARY_HASH`,NULL AS `NA_ERROR_DETAIL`,NULL AS `NU_ERROR_CLASSIFIER_VERSION`,`ht`.`NA_MESSAGE` AS `NA_RAW_MESSAGE` from (`BPDATA`.`HOST_TASK` `ht` left join `BPDATA`.`HOST` `h` on(`h`.`ID_HOST` = `ht`.`FK_HOST`)) where `ht`.`NU_STATUS` = -1;


-- The canonical refresh path is now the Python outbox worker
-- (`appCataloga_summary_database.py`). Legacy SQL functions, procedures,
-- and the MariaDB Event were removed from the bootstrap schema.
