/* =====================================================================
   createFusionSummaryDB-v1.sql
   Canonical RFFUSION_SUMMARY schema — current as of schema v3.

   Changelog
   ---------
   v1 — initial schema reconciled with the live MariaDB instance.
   v2 — geography keys (FK_COUNTY, FK_DISTRICT) promoted into
        SITE_EQUIPMENT_OBS_SUMMARY, HOST_LOCATION_SUMMARY and
        MAP_SITE_SUMMARY so features such as /spectrum, map payloads
        and host locality history can resolve district/county without
        joining back to live RFDATA dimension tables.
        (Previously delivered as alterFusionSummaryDB-v2-geography-keys.sql)
   v3 — current-month backup throughput by `DT_BACKUP` materialized into
        HOST_CURRENT_SNAPSHOT and aggregated into SERVER_CURRENT_SUMMARY via
        `NU_BACKUP_DONE_THIS_MONTH` and `VL_BACKUP_DONE_GB_THIS_MONTH`.
        This script is now the canonical source for that schema state; the
        transitional alter script is retired.

   Note on shadow tables
   ---------------------
   The summary worker uses an atomic-swap pattern (CREATE … SELECT, then
   RENAME TABLE) for heavy refreshes. The *_shadow tables it creates at
   runtime are transient and are therefore NOT defined here; the worker
   is responsible for their lifecycle.
   ===================================================================== */

CREATE DATABASE IF NOT EXISTS RFFUSION_SUMMARY
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE RFFUSION_SUMMARY;

-- Public refresh telemetry written by the Python summary worker.
CREATE TABLE `SUMMARY_REFRESH_STATE` (
  `NA_OBJECT_NAME` varchar(100) NOT NULL,
  `DT_LAST_START` datetime DEFAULT NULL,
  `DT_LAST_END` datetime DEFAULT NULL,
  `IS_SUCCESS` tinyint(1) NOT NULL DEFAULT 0,
  `NU_LAST_ROW_COUNT` bigint(20) DEFAULT NULL,
  `NA_SOURCE_HIGH_WATERMARK` varchar(255) DEFAULT NULL,
  `NA_ERROR_MESSAGE` text DEFAULT NULL,
  `DT_UPDATED_AT` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`NA_OBJECT_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `SUMMARY_REFRESH_LOG` (
  `ID_REFRESH_LOG` bigint(20) NOT NULL AUTO_INCREMENT,
  `NA_OBJECT_NAME` varchar(100) NOT NULL,
  `DT_STARTED_AT` datetime NOT NULL,
  `DT_FINISHED_AT` datetime DEFAULT NULL,
  `IS_SUCCESS` tinyint(1) NOT NULL DEFAULT 0,
  `NU_ROW_COUNT` bigint(20) DEFAULT NULL,
  `NA_SOURCE_HIGH_WATERMARK` varchar(255) DEFAULT NULL,
  `NA_ERROR_MESSAGE` text DEFAULT NULL,
  PRIMARY KEY (`ID_REFRESH_LOG`),
  KEY `IX_SUMMARY_REFRESH_LOG_OBJECT` (`NA_OBJECT_NAME`,`DT_STARTED_AT` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_EQUIPMENT_LINK_OVERRIDE` (
  `ID_OVERRIDE` bigint(20) NOT NULL AUTO_INCREMENT,
  `FK_HOST` int(11) NOT NULL,
  `FK_EQUIPMENT` int(11) NOT NULL,
  `NA_OVERRIDE_REASON` varchar(255) DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT 1,
  `DT_CREATED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  `DT_UPDATED_AT` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID_OVERRIDE`),
  UNIQUE KEY `UQ_HOST_EQUIPMENT_LINK_OVERRIDE` (`FK_HOST`,`FK_EQUIPMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_EQUIPMENT_LINK` (
  `ID_LINK` bigint(20) NOT NULL AUTO_INCREMENT,
  `FK_HOST` int(11) NOT NULL,
  `FK_EQUIPMENT` int(11) NOT NULL,
  `NA_HOST_NAME` varchar(100) NOT NULL,
  `NA_EQUIPMENT` varchar(100) NOT NULL,
  `NA_HOST_NAME_NORMALIZED` varchar(128) NOT NULL,
  `NA_EQUIPMENT_NAME_NORMALIZED` varchar(128) NOT NULL,
  `NA_HOST_SIGNATURE` varchar(128) DEFAULT NULL,
  `NA_EQUIPMENT_SIGNATURE` varchar(128) DEFAULT NULL,
  `NA_MATCH_TYPE` varchar(32) NOT NULL,
  `VL_MATCH_CONFIDENCE` decimal(5,2) NOT NULL DEFAULT 0.00,
  `IS_PRIMARY_LINK` tinyint(1) NOT NULL DEFAULT 0,
  `IS_MANUAL_OVERRIDE` tinyint(1) NOT NULL DEFAULT 0,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT 1,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID_LINK`),
  UNIQUE KEY `UQ_HOST_EQUIPMENT_LINK` (`FK_HOST`,`FK_EQUIPMENT`),
  KEY `IX_HOST_EQUIPMENT_LINK_HOST` (`FK_HOST`,`IS_ACTIVE`,`IS_PRIMARY_LINK`),
  KEY `IX_HOST_EQUIPMENT_LINK_EQUIPMENT` (`FK_EQUIPMENT`,`IS_ACTIVE`,`IS_PRIMARY_LINK`),
  KEY `IX_HOST_EQUIPMENT_LINK_MATCH` (`NA_MATCH_TYPE`,`VL_MATCH_CONFIDENCE` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `SITE_EQUIPMENT_OBS_SUMMARY` (
  `FK_SITE` int(11) NOT NULL,
  `FK_EQUIPMENT` int(11) NOT NULL,
  `NA_SITE_NAME` varchar(100) DEFAULT NULL,
  `NA_SITE_LABEL` varchar(120) NOT NULL,
  `FK_COUNTY` int(11) DEFAULT NULL,
  `FK_DISTRICT` int(11) DEFAULT NULL,
  `NA_COUNTY_NAME` varchar(150) DEFAULT NULL,
  `NA_DISTRICT_NAME` varchar(100) DEFAULT NULL,
  `ID_STATE` int(11) DEFAULT NULL,
  `NA_STATE_NAME` varchar(100) DEFAULT NULL,
  `NA_STATE_CODE` varchar(2) DEFAULT NULL,
  `VL_LATITUDE` decimal(10,7) DEFAULT NULL,
  `VL_LONGITUDE` decimal(10,7) DEFAULT NULL,
  `VL_ALTITUDE` decimal(10,3) DEFAULT NULL,
  `NU_GNSS_MEASUREMENTS` bigint(20) DEFAULT NULL,
  `NA_EQUIPMENT` varchar(100) DEFAULT NULL,
  `DT_FIRST_SEEN_AT` datetime DEFAULT NULL,
  `DT_LAST_SEEN_AT` datetime DEFAULT NULL,
  `NU_SPECTRUM_COUNT` bigint(20) NOT NULL DEFAULT 0,
  `ID_LAST_SPECTRUM` bigint(20) DEFAULT NULL,
  `IS_CURRENT_LOCATION` tinyint(1) NOT NULL DEFAULT 0,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`FK_SITE`,`FK_EQUIPMENT`),
  KEY `IX_SITE_EQUIPMENT_OBS_EQUIPMENT` (`FK_EQUIPMENT`,`IS_CURRENT_LOCATION`,`DT_LAST_SEEN_AT`),
  KEY `IX_SITE_EQUIPMENT_OBS_SITE` (`FK_SITE`,`DT_LAST_SEEN_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_LOCATION_SUMMARY` (
  `FK_HOST` int(11) NOT NULL,
  `FK_SITE` int(11) NOT NULL,
  `NA_HOST_NAME` varchar(100) NOT NULL,
  `NA_LOCALITY_LABEL` varchar(255) NOT NULL,
  `NA_SITE_LABEL` varchar(120) NOT NULL,
  `FK_COUNTY` int(11) DEFAULT NULL,
  `FK_DISTRICT` int(11) DEFAULT NULL,
  `NA_COUNTY_NAME` varchar(150) DEFAULT NULL,
  `NA_DISTRICT_NAME` varchar(100) DEFAULT NULL,
  `ID_STATE` int(11) DEFAULT NULL,
  `NA_STATE_NAME` varchar(100) DEFAULT NULL,
  `NA_STATE_CODE` varchar(2) DEFAULT NULL,
  `VL_LATITUDE` decimal(10,7) DEFAULT NULL,
  `VL_LONGITUDE` decimal(10,7) DEFAULT NULL,
  `VL_ALTITUDE` decimal(10,3) DEFAULT NULL,
  `DT_FIRST_SEEN_AT` datetime DEFAULT NULL,
  `DT_LAST_SEEN_AT` datetime DEFAULT NULL,
  `NU_SPECTRUM_COUNT` bigint(20) NOT NULL DEFAULT 0,
  `NU_MATCHED_EQUIPMENT_TOTAL` int(11) NOT NULL DEFAULT 0,
  `IS_CURRENT_LOCATION` tinyint(1) NOT NULL DEFAULT 0,
  `IS_OFFLINE_SNAPSHOT` tinyint(1) NOT NULL DEFAULT 0,
  `VL_MAX_MATCH_CONFIDENCE` decimal(5,2) DEFAULT NULL,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`FK_HOST`,`FK_SITE`),
  KEY `IX_HOST_LOCATION_CURRENT` (`FK_HOST`,`IS_CURRENT_LOCATION`,`DT_LAST_SEEN_AT`),
  KEY `IX_HOST_LOCATION_SITE` (`FK_SITE`,`DT_LAST_SEEN_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `MAP_SITE_STATION_SUMMARY` (
  `FK_SITE` int(11) NOT NULL,
  `FK_EQUIPMENT` int(11) NOT NULL,
  `FK_HOST` int(11) DEFAULT NULL,
  `NA_SITE_LABEL` varchar(120) NOT NULL,
  `NA_EQUIPMENT` varchar(100) DEFAULT NULL,
  `NA_HOST_NAME` varchar(100) DEFAULT NULL,
  `IS_OFFLINE` tinyint(1) DEFAULT NULL,
  `IS_CURRENT_LOCATION` tinyint(1) NOT NULL DEFAULT 0,
  `NA_MAP_STATE` varchar(32) NOT NULL,
  `NU_STATE_PRIORITY` smallint(6) NOT NULL DEFAULT 4,
  `DT_FIRST_SEEN_AT` datetime DEFAULT NULL,
  `DT_LAST_SEEN_AT` datetime DEFAULT NULL,
  `NU_SPECTRUM_COUNT` bigint(20) NOT NULL DEFAULT 0,
  `NA_MATCH_TYPE` varchar(32) DEFAULT NULL,
  `VL_MATCH_CONFIDENCE` decimal(5,2) DEFAULT NULL,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`FK_SITE`,`FK_EQUIPMENT`),
  KEY `IX_MAP_SITE_STATION_SITE` (`FK_SITE`,`NU_STATE_PRIORITY`,`NA_HOST_NAME`),
  KEY `IX_MAP_SITE_STATION_HOST` (`FK_HOST`,`NA_MAP_STATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `MAP_SITE_SUMMARY` (
  `FK_SITE` int(11) NOT NULL,
  `NA_SITE_LABEL` varchar(120) NOT NULL,
  `FK_COUNTY` int(11) DEFAULT NULL,
  `FK_DISTRICT` int(11) DEFAULT NULL,
  `NA_COUNTY_NAME` varchar(150) DEFAULT NULL,
  `NA_DISTRICT_NAME` varchar(100) DEFAULT NULL,
  `ID_STATE` int(11) DEFAULT NULL,
  `NA_STATE_NAME` varchar(100) DEFAULT NULL,
  `NA_STATE_CODE` varchar(2) DEFAULT NULL,
  `VL_LATITUDE` decimal(10,7) DEFAULT NULL,
  `VL_LONGITUDE` decimal(10,7) DEFAULT NULL,
  `VL_ALTITUDE` decimal(10,3) DEFAULT NULL,
  `NU_GNSS_MEASUREMENTS` bigint(20) DEFAULT NULL,
  `NA_MARKER_STATE` varchar(32) NOT NULL DEFAULT 'no_host',
  `NU_STATION_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_KNOWN_HOST_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_ONLINE_CURRENT_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_ONLINE_PREVIOUS_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_OFFLINE_CURRENT_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_OFFLINE_PREVIOUS_COUNT` int(11) NOT NULL DEFAULT 0,
  `NU_NO_HOST_COUNT` int(11) NOT NULL DEFAULT 0,
  `HAS_ONLINE_STATION` tinyint(1) NOT NULL DEFAULT 0,
  `HAS_ONLINE_HOST` tinyint(1) NOT NULL DEFAULT 0,
  `HAS_KNOWN_HOST` tinyint(1) NOT NULL DEFAULT 0,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`FK_SITE`),
  KEY `IX_MAP_SITE_SUMMARY_STATE` (`NA_MARKER_STATE`,`NA_STATE_CODE`),
  KEY `IX_MAP_SITE_SUMMARY_LOCATION` (`NA_COUNTY_NAME`,`NA_STATE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_MONTHLY_METRIC` (
  `FK_HOST` int(11) NOT NULL,
  `DT_REFERENCE_MONTH` date NOT NULL,
  `NA_HOST_NAME` varchar(100) NOT NULL,
  `NU_DISCOVERED_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_DISCOVERED_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_BACKUP_DONE_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_BACKUP_DONE_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_BACKUP_PENDING_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_BACKUP_PENDING_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_BACKUP_ERROR_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_BACKUP_ERROR_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_PROCESSING_DONE_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_PROCESSING_DONE_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_PROCESSING_PENDING_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_PROCESSING_PENDING_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_PROCESSING_ERROR_FILES` int(11) NOT NULL DEFAULT 0,
  `VL_PROCESSING_ERROR_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`FK_HOST`,`DT_REFERENCE_MONTH`),
  KEY `IX_HOST_MONTHLY_METRIC_MONTH` (`DT_REFERENCE_MONTH`,`FK_HOST`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_ERROR_SUMMARY` (
  `ID_HOST_ERROR_SUMMARY` bigint(20) NOT NULL AUTO_INCREMENT,
  `FK_HOST` int(11) NOT NULL,
  `NA_HOST_NAME` varchar(100) NOT NULL,
  `NA_ERROR_SCOPE` varchar(32) NOT NULL,
  `NA_ERROR_DOMAIN` varchar(32) DEFAULT NULL,
  `NA_ERROR_STAGE` varchar(32) DEFAULT NULL,
  `NA_ERROR_CODE` varchar(64) DEFAULT NULL,
  `NA_ERROR_SUMMARY_HASH` char(64) NOT NULL,
  `NA_ERROR_SUMMARY` text DEFAULT NULL,
  `NU_ERROR_COUNT` bigint(20) NOT NULL DEFAULT 0,
  `DT_FIRST_SEEN_AT` datetime DEFAULT NULL,
  `DT_LAST_SEEN_AT` datetime DEFAULT NULL,
  `NA_LAST_SOURCE_TABLE` varchar(32) DEFAULT NULL,
  `ID_LAST_SOURCE_ROW` bigint(20) DEFAULT NULL,
  `NA_LAST_ERROR_DETAIL` text DEFAULT NULL,
  `NA_LAST_RAW_MESSAGE` text DEFAULT NULL,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID_HOST_ERROR_SUMMARY`),
  UNIQUE KEY `UQ_HOST_ERROR_SUMMARY` (`FK_HOST`,`NA_ERROR_SCOPE`,`NA_ERROR_DOMAIN`,`NA_ERROR_STAGE`,`NA_ERROR_CODE`,`NA_ERROR_SUMMARY_HASH`),
  KEY `IX_HOST_ERROR_SUMMARY_HOST` (`FK_HOST`,`NA_ERROR_SCOPE`,`NU_ERROR_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `SERVER_ERROR_SUMMARY` (
  `ID_SERVER_ERROR_SUMMARY` bigint(20) NOT NULL AUTO_INCREMENT,
  `NA_ERROR_SCOPE` varchar(32) NOT NULL,
  `NA_ERROR_DOMAIN` varchar(32) DEFAULT NULL,
  `NA_ERROR_STAGE` varchar(32) DEFAULT NULL,
  `NA_ERROR_CODE` varchar(64) DEFAULT NULL,
  `NA_ERROR_SUMMARY_HASH` char(64) NOT NULL,
  `NA_ERROR_SUMMARY` text DEFAULT NULL,
  `NU_ERROR_COUNT` bigint(20) NOT NULL DEFAULT 0,
  `DT_FIRST_SEEN_AT` datetime DEFAULT NULL,
  `DT_LAST_SEEN_AT` datetime DEFAULT NULL,
  `NA_LAST_SOURCE_TABLE` varchar(32) DEFAULT NULL,
  `ID_LAST_SOURCE_ROW` bigint(20) DEFAULT NULL,
  `NA_LAST_ERROR_DETAIL` text DEFAULT NULL,
  `NA_LAST_RAW_MESSAGE` text DEFAULT NULL,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID_SERVER_ERROR_SUMMARY`),
  UNIQUE KEY `UQ_SERVER_ERROR_SUMMARY` (`NA_ERROR_SCOPE`,`NA_ERROR_DOMAIN`,`NA_ERROR_STAGE`,`NA_ERROR_CODE`,`NA_ERROR_SUMMARY_HASH`),
  KEY `IX_SERVER_ERROR_SUMMARY_SCOPE` (`NA_ERROR_SCOPE`,`NU_ERROR_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `HOST_CURRENT_SNAPSHOT` (
  `ID_HOST` int(11) NOT NULL,
  `NA_HOST_NAME` varchar(100) NOT NULL,
  `NA_HOST_ADDRESS` varchar(50) DEFAULT NULL,
  `NA_HOST_PORT` int(11) DEFAULT NULL,
  `IS_OFFLINE` tinyint(1) NOT NULL DEFAULT 0,
  `IS_BUSY` tinyint(1) NOT NULL DEFAULT 0,
  `NU_PID` int(11) DEFAULT NULL,
  `DT_BUSY` datetime DEFAULT NULL,
  `DT_LAST_FAIL` datetime DEFAULT NULL,
  `DT_LAST_CHECK` datetime DEFAULT NULL,
  `NU_HOST_CHECK_ERROR` int(11) DEFAULT NULL,
  `DT_LAST_DISCOVERY` datetime DEFAULT NULL,
  `NU_DONE_FILE_DISCOVERY_TASKS` int(11) DEFAULT NULL,
  `NU_ERROR_FILE_DISCOVERY_TASKS` int(11) DEFAULT NULL,
  `DT_LAST_BACKUP` datetime DEFAULT NULL,
  `NU_PENDING_FILE_BACKUP_TASKS` int(11) DEFAULT NULL,
  `NU_DONE_FILE_BACKUP_TASKS` int(11) DEFAULT NULL,
  `NU_ERROR_FILE_BACKUP_TASKS` int(11) DEFAULT NULL,
  `NU_BACKUP_DONE_THIS_MONTH` int(11) NOT NULL DEFAULT 0,
  `VL_PENDING_BACKUP_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `VL_BACKUP_DONE_GB_THIS_MONTH` decimal(18,2) NOT NULL DEFAULT 0.00,
  `VL_DONE_BACKUP_GB` decimal(18,2) NOT NULL DEFAULT 0.00,
  `DT_LAST_PROCESSING` datetime DEFAULT NULL,
  `NU_PENDING_FILE_PROCESS_TASKS` int(11) DEFAULT NULL,
  `NU_DONE_FILE_PROCESS_TASKS` int(11) DEFAULT NULL,
  `NU_ERROR_FILE_PROCESS_TASKS` int(11) DEFAULT NULL,
  `NU_HOST_FILES` int(11) DEFAULT NULL,
  `NU_BACKUP_QUEUE_FILES_TOTAL` int(11) NOT NULL DEFAULT 0,
  `VL_BACKUP_QUEUE_GB_TOTAL` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_PROCESSING_QUEUE_FILES_TOTAL` int(11) NOT NULL DEFAULT 0,
  `VL_PROCESSING_QUEUE_GB_TOTAL` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_MATCHED_EQUIPMENT_TOTAL` int(11) NOT NULL DEFAULT 0,
  `NU_FACT_SPECTRUM_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `FK_CURRENT_SITE` int(11) DEFAULT NULL,
  `NA_CURRENT_SITE_LABEL` varchar(120) DEFAULT NULL,
  `NA_CURRENT_STATE_CODE` varchar(2) DEFAULT NULL,
  `VL_CURRENT_LATITUDE` decimal(10,7) DEFAULT NULL,
  `VL_CURRENT_LONGITUDE` decimal(10,7) DEFAULT NULL,
  `DT_CURRENT_SITE_LAST_SEEN` datetime DEFAULT NULL,
  `NA_LAST_ERROR_SCOPE` varchar(32) DEFAULT NULL,
  `NA_LAST_ERROR_CODE` varchar(64) DEFAULT NULL,
  `NA_LAST_ERROR_SUMMARY` text DEFAULT NULL,
  `DT_LAST_ERROR_AT` datetime DEFAULT NULL,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID_HOST`),
  KEY `IX_HOST_CURRENT_SNAPSHOT_STATUS` (`IS_OFFLINE`,`IS_BUSY`,`NA_HOST_NAME`),
  KEY `IX_HOST_CURRENT_SNAPSHOT_SITE` (`FK_CURRENT_SITE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `SERVER_CURRENT_SUMMARY` (
  `ID_SUMMARY` tinyint(4) NOT NULL,
  `NA_CURRENT_MONTH_LABEL` char(7) NOT NULL,
  `NU_TOTAL_HOSTS` int(11) NOT NULL DEFAULT 0,
  `NU_ONLINE_HOSTS` int(11) NOT NULL DEFAULT 0,
  `NU_OFFLINE_HOSTS` int(11) NOT NULL DEFAULT 0,
  `NU_BUSY_HOSTS` int(11) NOT NULL DEFAULT 0,
  `NU_DISCOVERED_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_BACKUP_PENDING_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `VL_BACKUP_PENDING_GB_TOTAL` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_BACKUP_ERROR_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_BACKUP_QUEUE_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `VL_BACKUP_QUEUE_GB_TOTAL` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_PROCESSING_PENDING_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_PROCESSING_DONE_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_PROCESSING_ERROR_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_PROCESSING_QUEUE_FILES_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `VL_PROCESSING_QUEUE_GB_TOTAL` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_FACT_SPECTRUM_TOTAL` bigint(20) NOT NULL DEFAULT 0,
  `NU_BACKUP_DONE_THIS_MONTH` bigint(20) NOT NULL DEFAULT 0,
  `VL_BACKUP_DONE_GB_THIS_MONTH` decimal(18,2) NOT NULL DEFAULT 0.00,
  `NU_BACKUP_ERROR_GROUPS` int(11) NOT NULL DEFAULT 0,
  `NU_PROCESSING_ERROR_GROUPS` int(11) NOT NULL DEFAULT 0,
  `DT_REFRESHED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID_SUMMARY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `RFFUSION_SUMMARY`.`VW_ERROR_EVENT_CANONICAL` AS select 'FILE_TASK_HISTORY' AS `NA_SOURCE_TABLE`,`f`.`ID_HISTORY` AS `ID_SOURCE_ROW`,'BACKUP' AS `NA_ERROR_SCOPE`,`f`.`FK_HOST` AS `FK_HOST`,`h`.`NA_HOST_NAME` AS `NA_HOST_NAME`,coalesce(`f`.`DT_BACKUP`,`f`.`DT_DISCOVERED`,`f`.`DT_FILE_CREATED`,`f`.`DT_FILE_MODIFIED`) AS `DT_EVENT_AT`,`f`.`NU_STATUS_BACKUP` AS `NU_STATUS_VALUE`,nullif(trim(`f`.`NA_ERROR_DOMAIN`),'') AS `NA_ERROR_DOMAIN`,nullif(trim(`f`.`NA_ERROR_STAGE`),'') AS `NA_ERROR_STAGE`,nullif(trim(`f`.`NA_ERROR_CODE`),'') AS `NA_ERROR_CODE`,coalesce(nullif(trim(`f`.`NA_ERROR_SUMMARY`),''),nullif(trim(`f`.`NA_MESSAGE`),''),'(Sem mensagem)') AS `NA_ERROR_SUMMARY`,sha2(coalesce(nullif(trim(`f`.`NA_ERROR_SUMMARY`),''),nullif(trim(`f`.`NA_MESSAGE`),''),'(Sem mensagem)'),256) AS `NA_ERROR_SUMMARY_HASH`,`f`.`NA_ERROR_DETAIL` AS `NA_ERROR_DETAIL`,`f`.`NU_ERROR_CLASSIFIER_VERSION` AS `NU_ERROR_CLASSIFIER_VERSION`,`f`.`NA_MESSAGE` AS `NA_RAW_MESSAGE` from (`BPDATA`.`FILE_TASK_HISTORY` `f` left join `BPDATA`.`HOST` `h` on(`h`.`ID_HOST` = `f`.`FK_HOST`)) where `f`.`NU_STATUS_BACKUP` = -1 union all select 'FILE_TASK_HISTORY' AS `NA_SOURCE_TABLE`,`f`.`ID_HISTORY` AS `ID_SOURCE_ROW`,'PROCESSING' AS `NA_ERROR_SCOPE`,`f`.`FK_HOST` AS `FK_HOST`,`h`.`NA_HOST_NAME` AS `NA_HOST_NAME`,coalesce(`f`.`DT_PROCESSED`,`f`.`DT_BACKUP`,`f`.`DT_DISCOVERED`,`f`.`DT_FILE_CREATED`,`f`.`DT_FILE_MODIFIED`) AS `DT_EVENT_AT`,`f`.`NU_STATUS_PROCESSING` AS `NU_STATUS_VALUE`,nullif(trim(`f`.`NA_ERROR_DOMAIN`),'') AS `NA_ERROR_DOMAIN`,nullif(trim(`f`.`NA_ERROR_STAGE`),'') AS `NA_ERROR_STAGE`,nullif(trim(`f`.`NA_ERROR_CODE`),'') AS `NA_ERROR_CODE`,coalesce(nullif(trim(`f`.`NA_ERROR_SUMMARY`),''),nullif(trim(`f`.`NA_MESSAGE`),''),'(Sem mensagem)') AS `NA_ERROR_SUMMARY`,sha2(coalesce(nullif(trim(`f`.`NA_ERROR_SUMMARY`),''),nullif(trim(`f`.`NA_MESSAGE`),''),'(Sem mensagem)'),256) AS `NA_ERROR_SUMMARY_HASH`,`f`.`NA_ERROR_DETAIL` AS `NA_ERROR_DETAIL`,`f`.`NU_ERROR_CLASSIFIER_VERSION` AS `NU_ERROR_CLASSIFIER_VERSION`,`f`.`NA_MESSAGE` AS `NA_RAW_MESSAGE` from (`BPDATA`.`FILE_TASK_HISTORY` `f` left join `BPDATA`.`HOST` `h` on(`h`.`ID_HOST` = `f`.`FK_HOST`)) where `f`.`NU_STATUS_PROCESSING` = -1 union all select 'FILE_TASK' AS `NA_SOURCE_TABLE`,`t`.`ID_FILE_TASK` AS `ID_SOURCE_ROW`,case when `t`.`NU_TYPE` = 1 then 'BACKUP_QUEUE' when `t`.`NU_TYPE` = 2 then 'PROCESSING_QUEUE' else 'FILE_TASK' end AS `NA_ERROR_SCOPE`,`t`.`FK_HOST` AS `FK_HOST`,`h`.`NA_HOST_NAME` AS `NA_HOST_NAME`,coalesce(`t`.`DT_FILE_TASK`,`t`.`DT_FILE_CREATED`,`t`.`DT_FILE_MODIFIED`) AS `DT_EVENT_AT`,`t`.`NU_STATUS` AS `NU_STATUS_VALUE`,nullif(trim(`t`.`NA_ERROR_DOMAIN`),'') AS `NA_ERROR_DOMAIN`,nullif(trim(`t`.`NA_ERROR_STAGE`),'') AS `NA_ERROR_STAGE`,nullif(trim(`t`.`NA_ERROR_CODE`),'') AS `NA_ERROR_CODE`,coalesce(nullif(trim(`t`.`NA_ERROR_SUMMARY`),''),nullif(trim(`t`.`NA_MESSAGE`),''),'(Sem mensagem)') AS `NA_ERROR_SUMMARY`,sha2(coalesce(nullif(trim(`t`.`NA_ERROR_SUMMARY`),''),nullif(trim(`t`.`NA_MESSAGE`),''),'(Sem mensagem)'),256) AS `NA_ERROR_SUMMARY_HASH`,`t`.`NA_ERROR_DETAIL` AS `NA_ERROR_DETAIL`,`t`.`NU_ERROR_CLASSIFIER_VERSION` AS `NU_ERROR_CLASSIFIER_VERSION`,`t`.`NA_MESSAGE` AS `NA_RAW_MESSAGE` from (`BPDATA`.`FILE_TASK` `t` left join `BPDATA`.`HOST` `h` on(`h`.`ID_HOST` = `t`.`FK_HOST`)) where `t`.`NU_STATUS` = -1 union all select 'HOST_TASK' AS `NA_SOURCE_TABLE`,`ht`.`ID_HOST_TASK` AS `ID_SOURCE_ROW`,'HOST_TASK' AS `NA_ERROR_SCOPE`,`ht`.`FK_HOST` AS `FK_HOST`,`h`.`NA_HOST_NAME` AS `NA_HOST_NAME`,`ht`.`DT_HOST_TASK` AS `DT_EVENT_AT`,`ht`.`NU_STATUS` AS `NU_STATUS_VALUE`,NULL AS `NA_ERROR_DOMAIN`,NULL AS `NA_ERROR_STAGE`,NULL AS `NA_ERROR_CODE`,coalesce(nullif(trim(`ht`.`NA_MESSAGE`),''),'(Sem mensagem)') AS `NA_ERROR_SUMMARY`,sha2(coalesce(nullif(trim(`ht`.`NA_MESSAGE`),''),'(Sem mensagem)'),256) AS `NA_ERROR_SUMMARY_HASH`,NULL AS `NA_ERROR_DETAIL`,NULL AS `NU_ERROR_CLASSIFIER_VERSION`,`ht`.`NA_MESSAGE` AS `NA_RAW_MESSAGE` from (`BPDATA`.`HOST_TASK` `ht` left join `BPDATA`.`HOST` `h` on(`h`.`ID_HOST` = `ht`.`FK_HOST`)) where `ht`.`NU_STATUS` = -1;

DELIMITER $$

CREATE FUNCTION `FN_SUMMARY_NORMALIZE_KEY`(p_value VARCHAR(255)) RETURNS varchar(255) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci
    DETERMINISTIC
BEGIN
    DECLARE v_value VARCHAR(255);

    SET v_value = LOWER(TRIM(COALESCE(p_value, '')));
    SET v_value = REPLACE(v_value, '-', '');
    SET v_value = REPLACE(v_value, '_', '');
    SET v_value = REPLACE(v_value, '.', '');
    SET v_value = REPLACE(v_value, ' ', '');
    SET v_value = REPLACE(v_value, '/', '');
    SET v_value = REPLACE(v_value, ':', '');
    SET v_value = REPLACE(v_value, ';', '');
    SET v_value = REPLACE(v_value, ',', '');
    SET v_value = REPLACE(v_value, '(', '');
    SET v_value = REPLACE(v_value, ')', '');
    SET v_value = REPLACE(v_value, '[', '');
    SET v_value = REPLACE(v_value, ']', '');

    RETURN v_value;
END$$

CREATE FUNCTION `FN_SUMMARY_CWSM_SIGNATURE`(p_normalized_key VARCHAR(255)) RETURNS varchar(255) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci
    DETERMINISTIC
BEGIN
    DECLARE v_digits VARCHAR(255);
    DECLARE v_station_suffix INT;
    DECLARE v_prefix VARCHAR(4);

    IF p_normalized_key IS NULL OR p_normalized_key = '' THEN
        RETURN NULL;
    END IF;

    IF LEFT(p_normalized_key, 4) <> 'cwsm' THEN
        RETURN NULL;
    END IF;

    SET v_digits = SUBSTRING(p_normalized_key, 5);

    IF v_digits = '' OR v_digits REGEXP '[^0-9]' THEN
        RETURN NULL;
    END IF;

    IF CHAR_LENGTH(v_digits) < 6 THEN
        RETURN NULL;
    END IF;

    IF v_digits = '22010007' THEN
        RETURN 'cwsm211007';
    END IF;

    IF CHAR_LENGTH(v_digits) >= 8 THEN
        SET v_station_suffix = CAST(RIGHT(v_digits, 2) AS UNSIGNED);

        -- CelPlan allocates short host families by station suffix range, so
        -- some historical `cwsm2110xxxx` receivers belong to `CWSM212xxx` or
        -- `CWSM220xxx` hosts instead of `CWSM211xxx`.
        IF v_station_suffix BETWEEN 1 AND 22 THEN
            RETURN CONCAT('cwsm211', RIGHT(v_digits, 3));
        END IF;

        IF v_station_suffix BETWEEN 26 AND 37 THEN
            RETURN CONCAT('cwsm212', RIGHT(v_digits, 3));
        END IF;

        IF v_station_suffix BETWEEN 38 AND 47 THEN
            RETURN CONCAT('cwsm220', RIGHT(v_digits, 3));
        END IF;

        SET v_prefix = LEFT(v_digits, 4);

        IF v_prefix = '2110' THEN
            RETURN CONCAT('cwsm211', RIGHT(v_digits, 3));
        END IF;

        IF v_prefix = '2112' THEN
            RETURN CONCAT('cwsm212', RIGHT(v_digits, 3));
        END IF;

        IF v_prefix = '2201' THEN
            RETURN CONCAT('cwsm220', RIGHT(v_digits, 3));
        END IF;
    END IF;

    RETURN CONCAT('cwsm', LEFT(v_digits, 3), RIGHT(v_digits, 3));
END$$

CREATE FUNCTION `FN_SUMMARY_MAP_STATE`(p_is_host_known TINYINT,
    p_is_offline TINYINT,
    p_is_current_location TINYINT
) RETURNS varchar(32) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci
    DETERMINISTIC
BEGIN
    IF COALESCE(p_is_host_known, 0) = 0 THEN
        RETURN 'no_host';
    END IF;

    IF COALESCE(p_is_offline, 0) = 1 THEN
        IF COALESCE(p_is_current_location, 0) = 1 THEN
            RETURN 'offline_current';
        END IF;

        RETURN 'offline_previous';
    END IF;

    IF COALESCE(p_is_current_location, 0) = 1 THEN
        RETURN 'online_current';
    END IF;

    RETURN 'online_previous';
END$$

CREATE FUNCTION `FN_SUMMARY_MAP_STATE_PRIORITY`(p_state VARCHAR(32)) RETURNS smallint(6)
    DETERMINISTIC
BEGIN
    IF p_state = 'online_current' THEN
        RETURN 0;
    END IF;

    IF p_state = 'online_previous' THEN
        RETURN 1;
    END IF;

    IF p_state = 'offline_current' THEN
        RETURN 2;
    END IF;

    IF p_state = 'offline_previous' THEN
        RETURN 3;
    END IF;

    RETURN 4;
END$$

CREATE PROCEDURE `PRC_REFRESH_HOST_EQUIPMENT_LINK_FULL`()
BEGIN
    DECLARE v_started_at DATETIME DEFAULT UTC_TIMESTAMP();
    DECLARE v_row_count BIGINT DEFAULT 0;

    INSERT INTO SUMMARY_REFRESH_STATE (
        NA_OBJECT_NAME,
        DT_LAST_START,
        DT_LAST_END,
        IS_SUCCESS,
        NU_LAST_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        'HOST_EQUIPMENT_LINK',
        v_started_at,
        NULL,
        0,
        NULL,
        NULL,
        NULL
    )
    ON DUPLICATE KEY UPDATE
        DT_LAST_START = VALUES(DT_LAST_START),
        DT_LAST_END = VALUES(DT_LAST_END),
        IS_SUCCESS = VALUES(IS_SUCCESS),
        NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
        NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
        NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

    DROP TEMPORARY TABLE IF EXISTS TMP_HOST_KEYS;
    DROP TEMPORARY TABLE IF EXISTS TMP_EQUIPMENT_KEYS;
    DROP TEMPORARY TABLE IF EXISTS TMP_LINK_CANDIDATES;
    DROP TEMPORARY TABLE IF EXISTS TMP_LINK_BEST;

    CREATE TEMPORARY TABLE TMP_HOST_KEYS AS
    SELECT
        h.ID_HOST AS FK_HOST,
        h.NA_HOST_NAME,
        FN_SUMMARY_NORMALIZE_KEY(h.NA_HOST_NAME) AS NA_HOST_NAME_NORMALIZED,
        FN_SUMMARY_CWSM_SIGNATURE(FN_SUMMARY_NORMALIZE_KEY(h.NA_HOST_NAME)) AS NA_HOST_SIGNATURE
    FROM BPDATA.HOST h
    WHERE h.NA_HOST_NAME IS NOT NULL
      AND TRIM(h.NA_HOST_NAME) <> '';

    CREATE TEMPORARY TABLE TMP_EQUIPMENT_KEYS AS
    SELECT
        e.ID_EQUIPMENT AS FK_EQUIPMENT,
        e.NA_EQUIPMENT,
        FN_SUMMARY_NORMALIZE_KEY(e.NA_EQUIPMENT) AS NA_EQUIPMENT_NAME_NORMALIZED,
        FN_SUMMARY_CWSM_SIGNATURE(FN_SUMMARY_NORMALIZE_KEY(e.NA_EQUIPMENT)) AS NA_EQUIPMENT_SIGNATURE
    FROM RFDATA.DIM_SPECTRUM_EQUIPMENT e
    WHERE e.NA_EQUIPMENT IS NOT NULL
      AND TRIM(e.NA_EQUIPMENT) <> '';

    CREATE TEMPORARY TABLE TMP_LINK_CANDIDATES (
        FK_HOST INT NOT NULL,
        FK_EQUIPMENT INT NOT NULL,
        NA_HOST_NAME VARCHAR(100) NOT NULL,
        NA_EQUIPMENT VARCHAR(100) NOT NULL,
        NA_HOST_NAME_NORMALIZED VARCHAR(128) NOT NULL,
        NA_EQUIPMENT_NAME_NORMALIZED VARCHAR(128) NOT NULL,
        NA_HOST_SIGNATURE VARCHAR(128) DEFAULT NULL,
        NA_EQUIPMENT_SIGNATURE VARCHAR(128) DEFAULT NULL,
        NA_MATCH_TYPE VARCHAR(32) NOT NULL,
        VL_MATCH_CONFIDENCE DECIMAL(5,2) NOT NULL,
        IS_MANUAL_OVERRIDE TINYINT(1) NOT NULL DEFAULT 0
    ) CHARACTER SET utf8mb4;

    INSERT INTO TMP_LINK_CANDIDATES
    SELECT
        h.FK_HOST,
        e.FK_EQUIPMENT,
        h.NA_HOST_NAME,
        e.NA_EQUIPMENT,
        h.NA_HOST_NAME_NORMALIZED,
        e.NA_EQUIPMENT_NAME_NORMALIZED,
        h.NA_HOST_SIGNATURE,
        e.NA_EQUIPMENT_SIGNATURE,
        'exact_normalized',
        1.00,
        0
    FROM TMP_HOST_KEYS h
    JOIN TMP_EQUIPMENT_KEYS e
      ON h.NA_HOST_NAME_NORMALIZED <> ''
     AND h.NA_HOST_NAME_NORMALIZED = e.NA_EQUIPMENT_NAME_NORMALIZED;

    INSERT INTO TMP_LINK_CANDIDATES
    SELECT
        h.FK_HOST,
        e.FK_EQUIPMENT,
        h.NA_HOST_NAME,
        e.NA_EQUIPMENT,
        h.NA_HOST_NAME_NORMALIZED,
        e.NA_EQUIPMENT_NAME_NORMALIZED,
        h.NA_HOST_SIGNATURE,
        e.NA_EQUIPMENT_SIGNATURE,
        'cwsm_signature',
        0.95,
        0
    FROM TMP_HOST_KEYS h
    JOIN TMP_EQUIPMENT_KEYS e
      ON h.NA_HOST_SIGNATURE IS NOT NULL
     AND h.NA_HOST_SIGNATURE <> ''
     AND h.NA_HOST_SIGNATURE = e.NA_EQUIPMENT_SIGNATURE;

    INSERT INTO TMP_LINK_CANDIDATES
    SELECT
        h.FK_HOST,
        e.FK_EQUIPMENT,
        h.NA_HOST_NAME,
        e.NA_EQUIPMENT,
        h.NA_HOST_NAME_NORMALIZED,
        e.NA_EQUIPMENT_NAME_NORMALIZED,
        h.NA_HOST_SIGNATURE,
        e.NA_EQUIPMENT_SIGNATURE,
        'prefix_match',
        0.60,
        0
    FROM TMP_HOST_KEYS h
    JOIN TMP_EQUIPMENT_KEYS e
      ON CHAR_LENGTH(h.NA_HOST_NAME_NORMALIZED) >= 6
     AND CHAR_LENGTH(e.NA_EQUIPMENT_NAME_NORMALIZED) >= 6
     AND (
            h.NA_HOST_NAME_NORMALIZED LIKE CONCAT(e.NA_EQUIPMENT_NAME_NORMALIZED, '%')
         OR e.NA_EQUIPMENT_NAME_NORMALIZED LIKE CONCAT(h.NA_HOST_NAME_NORMALIZED, '%')
     );

    INSERT INTO TMP_LINK_CANDIDATES
    SELECT
        o.FK_HOST,
        o.FK_EQUIPMENT,
        h.NA_HOST_NAME,
        e.NA_EQUIPMENT,
        FN_SUMMARY_NORMALIZE_KEY(h.NA_HOST_NAME),
        FN_SUMMARY_NORMALIZE_KEY(e.NA_EQUIPMENT),
        FN_SUMMARY_CWSM_SIGNATURE(FN_SUMMARY_NORMALIZE_KEY(h.NA_HOST_NAME)),
        FN_SUMMARY_CWSM_SIGNATURE(FN_SUMMARY_NORMALIZE_KEY(e.NA_EQUIPMENT)),
        'manual_override',
        2.00,
        1
    FROM HOST_EQUIPMENT_LINK_OVERRIDE o
    JOIN BPDATA.HOST h
      ON h.ID_HOST = o.FK_HOST
    JOIN RFDATA.DIM_SPECTRUM_EQUIPMENT e
      ON e.ID_EQUIPMENT = o.FK_EQUIPMENT
    WHERE o.IS_ACTIVE = 1;

    CREATE TEMPORARY TABLE TMP_LINK_BEST AS
    SELECT
        ranked.FK_HOST,
        ranked.FK_EQUIPMENT,
        ranked.NA_HOST_NAME,
        ranked.NA_EQUIPMENT,
        ranked.NA_HOST_NAME_NORMALIZED,
        ranked.NA_EQUIPMENT_NAME_NORMALIZED,
        ranked.NA_HOST_SIGNATURE,
        ranked.NA_EQUIPMENT_SIGNATURE,
        ranked.NA_MATCH_TYPE,
        ranked.VL_MATCH_CONFIDENCE,
        ranked.IS_MANUAL_OVERRIDE,
        ROW_NUMBER() OVER (
            PARTITION BY ranked.FK_EQUIPMENT
            ORDER BY ranked.VL_MATCH_CONFIDENCE DESC, ranked.IS_MANUAL_OVERRIDE DESC, ranked.NA_MATCH_TYPE ASC, ranked.FK_HOST ASC
        ) AS RN_FOR_EQUIPMENT,
        COUNT(*) OVER (
            PARTITION BY ranked.FK_EQUIPMENT, ranked.VL_MATCH_CONFIDENCE, ranked.IS_MANUAL_OVERRIDE
        ) AS TIE_COUNT
    FROM (
        SELECT *
        FROM (
            SELECT
                c.*,
                ROW_NUMBER() OVER (
                    PARTITION BY c.FK_HOST, c.FK_EQUIPMENT
                    ORDER BY c.VL_MATCH_CONFIDENCE DESC, c.IS_MANUAL_OVERRIDE DESC, c.NA_MATCH_TYPE ASC
                ) AS RN_LINK
            FROM TMP_LINK_CANDIDATES c
        ) dedup
        WHERE dedup.RN_LINK = 1
    ) ranked;

    TRUNCATE TABLE HOST_EQUIPMENT_LINK;

    INSERT INTO HOST_EQUIPMENT_LINK (
        FK_HOST,
        FK_EQUIPMENT,
        NA_HOST_NAME,
        NA_EQUIPMENT,
        NA_HOST_NAME_NORMALIZED,
        NA_EQUIPMENT_NAME_NORMALIZED,
        NA_HOST_SIGNATURE,
        NA_EQUIPMENT_SIGNATURE,
        NA_MATCH_TYPE,
        VL_MATCH_CONFIDENCE,
        IS_PRIMARY_LINK,
        IS_MANUAL_OVERRIDE,
        IS_ACTIVE,
        DT_REFRESHED_AT
    )
    SELECT
        FK_HOST,
        FK_EQUIPMENT,
        NA_HOST_NAME,
        NA_EQUIPMENT,
        NA_HOST_NAME_NORMALIZED,
        NA_EQUIPMENT_NAME_NORMALIZED,
        NA_HOST_SIGNATURE,
        NA_EQUIPMENT_SIGNATURE,
        NA_MATCH_TYPE,
        VL_MATCH_CONFIDENCE,
        CASE
            WHEN RN_FOR_EQUIPMENT = 1 AND TIE_COUNT = 1 THEN 1
            ELSE 0
        END,
        IS_MANUAL_OVERRIDE,
        1,
        UTC_TIMESTAMP()
    FROM TMP_LINK_BEST;

    SET v_row_count = (SELECT COUNT(*) FROM HOST_EQUIPMENT_LINK);

    UPDATE SUMMARY_REFRESH_STATE
    SET
        DT_LAST_END = UTC_TIMESTAMP(),
        IS_SUCCESS = 1,
        NU_LAST_ROW_COUNT = v_row_count,
        NA_SOURCE_HIGH_WATERMARK = CONCAT(
            'hosts=',
            (SELECT COUNT(*) FROM BPDATA.HOST),
            ';equipments=',
            (SELECT COUNT(*) FROM RFDATA.DIM_SPECTRUM_EQUIPMENT)
        ),
        NA_ERROR_MESSAGE = NULL
    WHERE NA_OBJECT_NAME = 'HOST_EQUIPMENT_LINK';

    INSERT INTO SUMMARY_REFRESH_LOG (
        NA_OBJECT_NAME,
        DT_STARTED_AT,
        DT_FINISHED_AT,
        IS_SUCCESS,
        NU_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        'HOST_EQUIPMENT_LINK',
        v_started_at,
        UTC_TIMESTAMP(),
        1,
        v_row_count,
        CONCAT(
            'hosts=',
            (SELECT COUNT(*) FROM BPDATA.HOST),
            ';equipments=',
            (SELECT COUNT(*) FROM RFDATA.DIM_SPECTRUM_EQUIPMENT)
        ),
        NULL
    );

    DROP TEMPORARY TABLE IF EXISTS TMP_LINK_BEST;
    DROP TEMPORARY TABLE IF EXISTS TMP_LINK_CANDIDATES;
    DROP TEMPORARY TABLE IF EXISTS TMP_EQUIPMENT_KEYS;
    DROP TEMPORARY TABLE IF EXISTS TMP_HOST_KEYS;
END$$

CREATE PROCEDURE `PRC_REFRESH_SITE_EQUIPMENT_OBS_SUMMARY_FULL`()
BEGIN
    DECLARE v_started_at DATETIME DEFAULT UTC_TIMESTAMP();
    DECLARE v_row_count BIGINT DEFAULT 0;

    INSERT INTO SUMMARY_REFRESH_STATE (
        NA_OBJECT_NAME,
        DT_LAST_START,
        DT_LAST_END,
        IS_SUCCESS,
        NU_LAST_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES ('SITE_EQUIPMENT_OBS_SUMMARY', v_started_at, NULL, 0, NULL, NULL, NULL)
    ON DUPLICATE KEY UPDATE
        DT_LAST_START = VALUES(DT_LAST_START),
        DT_LAST_END = VALUES(DT_LAST_END),
        IS_SUCCESS = VALUES(IS_SUCCESS),
        NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
        NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
        NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

    DROP TABLE IF EXISTS SITE_EQUIPMENT_OBS_SUMMARY__BUILD;
    DROP TABLE IF EXISTS SITE_EQUIPMENT_OBS_SUMMARY__OLD;
    CREATE TABLE SITE_EQUIPMENT_OBS_SUMMARY__BUILD LIKE SITE_EQUIPMENT_OBS_SUMMARY;

    INSERT INTO SITE_EQUIPMENT_OBS_SUMMARY__BUILD (
        FK_SITE,
        FK_EQUIPMENT,
        NA_SITE_NAME,
        NA_SITE_LABEL,
        FK_COUNTY,
        FK_DISTRICT,
        NA_COUNTY_NAME,
        NA_DISTRICT_NAME,
        ID_STATE,
        NA_STATE_NAME,
        NA_STATE_CODE,
        VL_LATITUDE,
        VL_LONGITUDE,
        VL_ALTITUDE,
        NU_GNSS_MEASUREMENTS,
        NA_EQUIPMENT,
        DT_FIRST_SEEN_AT,
        DT_LAST_SEEN_AT,
        NU_SPECTRUM_COUNT,
        ID_LAST_SPECTRUM,
        IS_CURRENT_LOCATION,
        DT_REFRESHED_AT
    )
    SELECT
        ranked.FK_SITE,
        ranked.FK_EQUIPMENT,
        ranked.NA_SITE_NAME,
        ranked.NA_SITE_LABEL,
        ranked.FK_COUNTY,
        ranked.FK_DISTRICT,
        ranked.NA_COUNTY_NAME,
        ranked.NA_DISTRICT_NAME,
        ranked.ID_STATE,
        ranked.NA_STATE_NAME,
        ranked.NA_STATE_CODE,
        ranked.VL_LATITUDE,
        ranked.VL_LONGITUDE,
        ranked.VL_ALTITUDE,
        ranked.NU_GNSS_MEASUREMENTS,
        ranked.NA_EQUIPMENT,
        ranked.DT_FIRST_SEEN_AT,
        ranked.DT_LAST_SEEN_AT,
        ranked.NU_SPECTRUM_COUNT,
        ranked.ID_LAST_SPECTRUM,
        CASE
            WHEN ranked.RN_FOR_EQUIPMENT = 1 THEN 1
            ELSE 0
        END,
        UTC_TIMESTAMP()
    FROM (
        SELECT
            base.*,
            ROW_NUMBER() OVER (
                PARTITION BY base.FK_EQUIPMENT
                ORDER BY COALESCE(base.DT_LAST_SEEN_AT, base.DT_FIRST_SEEN_AT) DESC,
                         COALESCE(base.DT_FIRST_SEEN_AT, base.DT_LAST_SEEN_AT) DESC,
                         base.FK_SITE DESC
            ) AS RN_FOR_EQUIPMENT
        FROM (
            SELECT
                f.FK_SITE,
                f.FK_EQUIPMENT,
                s.NA_SITE AS NA_SITE_NAME,
                COALESCE(NULLIF(s.NA_SITE, ''), CONCAT('Site ', s.ID_SITE)) AS NA_SITE_LABEL,
                s.FK_COUNTY,
                s.FK_DISTRICT,
                c.NA_COUNTY AS NA_COUNTY_NAME,
                d.NA_DISTRICT AS NA_DISTRICT_NAME,
                st.ID_STATE,
                st.NA_STATE AS NA_STATE_NAME,
                st.LC_STATE AS NA_STATE_CODE,
                ST_Y(s.GEO_POINT) AS VL_LATITUDE,
                ST_X(s.GEO_POINT) AS VL_LONGITUDE,
                s.NU_ALTITUDE AS VL_ALTITUDE,
                s.NU_GNSS_MEASUREMENTS,
                e.NA_EQUIPMENT,
                MIN(f.DT_TIME_START) AS DT_FIRST_SEEN_AT,
                MAX(f.DT_TIME_END) AS DT_LAST_SEEN_AT,
                COUNT(*) AS NU_SPECTRUM_COUNT,
                MAX(f.ID_SPECTRUM) AS ID_LAST_SPECTRUM
            FROM RFDATA.FACT_SPECTRUM f
            JOIN RFDATA.DIM_SPECTRUM_EQUIPMENT e
              ON e.ID_EQUIPMENT = f.FK_EQUIPMENT
            JOIN RFDATA.DIM_SPECTRUM_SITE s
              ON s.ID_SITE = f.FK_SITE
            LEFT JOIN RFDATA.DIM_SITE_COUNTY c
              ON c.ID_COUNTY = s.FK_COUNTY
            LEFT JOIN RFDATA.DIM_SITE_DISTRICT d
              ON d.ID_DISTRICT = s.FK_DISTRICT
            LEFT JOIN RFDATA.DIM_SITE_STATE st
              ON st.ID_STATE = s.FK_STATE
            GROUP BY
                f.FK_SITE,
                f.FK_EQUIPMENT,
                s.NA_SITE,
                s.FK_COUNTY,
                s.FK_DISTRICT,
                c.NA_COUNTY,
                d.NA_DISTRICT,
                st.ID_STATE,
                st.NA_STATE,
                st.LC_STATE,
                ST_Y(s.GEO_POINT),
                ST_X(s.GEO_POINT),
                s.NU_ALTITUDE,
                s.NU_GNSS_MEASUREMENTS,
                e.NA_EQUIPMENT
        ) base
    ) ranked;

    SET v_row_count = (SELECT COUNT(*) FROM SITE_EQUIPMENT_OBS_SUMMARY__BUILD);

    RENAME TABLE
        SITE_EQUIPMENT_OBS_SUMMARY TO SITE_EQUIPMENT_OBS_SUMMARY__OLD,
        SITE_EQUIPMENT_OBS_SUMMARY__BUILD TO SITE_EQUIPMENT_OBS_SUMMARY;
    DROP TABLE SITE_EQUIPMENT_OBS_SUMMARY__OLD;

    UPDATE SUMMARY_REFRESH_STATE
    SET
        DT_LAST_END = UTC_TIMESTAMP(),
        IS_SUCCESS = 1,
        NU_LAST_ROW_COUNT = v_row_count,
        NA_SOURCE_HIGH_WATERMARK = CONCAT(
            'max_spectrum_id=',
            COALESCE((SELECT MAX(ID_SPECTRUM) FROM RFDATA.FACT_SPECTRUM), 0)
        ),
        NA_ERROR_MESSAGE = NULL
    WHERE NA_OBJECT_NAME = 'SITE_EQUIPMENT_OBS_SUMMARY';

    INSERT INTO SUMMARY_REFRESH_LOG (
        NA_OBJECT_NAME,
        DT_STARTED_AT,
        DT_FINISHED_AT,
        IS_SUCCESS,
        NU_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        'SITE_EQUIPMENT_OBS_SUMMARY',
        v_started_at,
        UTC_TIMESTAMP(),
        1,
        v_row_count,
        CONCAT(
            'max_spectrum_id=',
            COALESCE((SELECT MAX(ID_SPECTRUM) FROM RFDATA.FACT_SPECTRUM), 0)
        ),
        NULL
    );
END$$

CREATE PROCEDURE `PRC_REFRESH_HOST_LOCATION_SUMMARY_FULL`()
BEGIN
    DECLARE v_started_at DATETIME DEFAULT UTC_TIMESTAMP();
    DECLARE v_row_count BIGINT DEFAULT 0;

    INSERT INTO SUMMARY_REFRESH_STATE (
        NA_OBJECT_NAME,
        DT_LAST_START,
        DT_LAST_END,
        IS_SUCCESS,
        NU_LAST_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES ('HOST_LOCATION_SUMMARY', v_started_at, NULL, 0, NULL, NULL, NULL)
    ON DUPLICATE KEY UPDATE
        DT_LAST_START = VALUES(DT_LAST_START),
        DT_LAST_END = VALUES(DT_LAST_END),
        IS_SUCCESS = VALUES(IS_SUCCESS),
        NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
        NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
        NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

    DROP TABLE IF EXISTS HOST_LOCATION_SUMMARY__BUILD;
    DROP TABLE IF EXISTS HOST_LOCATION_SUMMARY__OLD;
    CREATE TABLE HOST_LOCATION_SUMMARY__BUILD LIKE HOST_LOCATION_SUMMARY;

    INSERT INTO HOST_LOCATION_SUMMARY__BUILD (
        FK_HOST,
        FK_SITE,
        NA_HOST_NAME,
        NA_LOCALITY_LABEL,
        NA_SITE_LABEL,
        FK_COUNTY,
        FK_DISTRICT,
        NA_COUNTY_NAME,
        NA_DISTRICT_NAME,
        ID_STATE,
        NA_STATE_NAME,
        NA_STATE_CODE,
        VL_LATITUDE,
        VL_LONGITUDE,
        VL_ALTITUDE,
        DT_FIRST_SEEN_AT,
        DT_LAST_SEEN_AT,
        NU_SPECTRUM_COUNT,
        NU_MATCHED_EQUIPMENT_TOTAL,
        IS_CURRENT_LOCATION,
        IS_OFFLINE_SNAPSHOT,
        VL_MAX_MATCH_CONFIDENCE,
        DT_REFRESHED_AT
    )
    SELECT
        link.FK_HOST,
        obs.FK_SITE,
        host.NA_HOST_NAME,
        TRIM(
            CONCAT(
                COALESCE(NULLIF(obs.NA_SITE_NAME, ''), NULLIF(obs.NA_DISTRICT_NAME, ''), obs.NA_COUNTY_NAME, CONCAT('Site ', obs.FK_SITE)),
                CASE
                    WHEN obs.NA_COUNTY_NAME IS NOT NULL
                     AND (
                            obs.NA_SITE_NAME IS NULL
                         OR obs.NA_SITE_NAME = ''
                         OR LOWER(obs.NA_SITE_NAME) <> LOWER(obs.NA_COUNTY_NAME)
                     )
                    THEN CONCAT(' · ', obs.NA_COUNTY_NAME)
                    ELSE ''
                END,
                CASE
                    WHEN obs.NA_STATE_CODE IS NOT NULL THEN CONCAT('/', obs.NA_STATE_CODE)
                    ELSE ''
                END
            )
        ) AS NA_LOCALITY_LABEL,
        obs.NA_SITE_LABEL,
        obs.FK_COUNTY,
        obs.FK_DISTRICT,
        obs.NA_COUNTY_NAME,
        obs.NA_DISTRICT_NAME,
        obs.ID_STATE,
        obs.NA_STATE_NAME,
        obs.NA_STATE_CODE,
        obs.VL_LATITUDE,
        obs.VL_LONGITUDE,
        obs.VL_ALTITUDE,
        MIN(obs.DT_FIRST_SEEN_AT),
        MAX(obs.DT_LAST_SEEN_AT),
        SUM(obs.NU_SPECTRUM_COUNT),
        COUNT(DISTINCT obs.FK_EQUIPMENT),
        MAX(obs.IS_CURRENT_LOCATION),
        MAX(COALESCE(host.IS_OFFLINE, 0)),
        MAX(link.VL_MATCH_CONFIDENCE),
        UTC_TIMESTAMP()
    FROM SITE_EQUIPMENT_OBS_SUMMARY obs
    JOIN HOST_EQUIPMENT_LINK link
      ON link.FK_EQUIPMENT = obs.FK_EQUIPMENT
     AND link.IS_ACTIVE = 1
     AND link.IS_PRIMARY_LINK = 1
    JOIN BPDATA.HOST host
      ON host.ID_HOST = link.FK_HOST
    GROUP BY
        link.FK_HOST,
        obs.FK_SITE,
        host.NA_HOST_NAME,
        obs.NA_SITE_NAME,
        obs.NA_SITE_LABEL,
        obs.FK_COUNTY,
        obs.FK_DISTRICT,
        obs.NA_COUNTY_NAME,
        obs.NA_DISTRICT_NAME,
        obs.ID_STATE,
        obs.NA_STATE_NAME,
        obs.NA_STATE_CODE,
        obs.VL_LATITUDE,
        obs.VL_LONGITUDE,
        obs.VL_ALTITUDE;

    SET v_row_count = (SELECT COUNT(*) FROM HOST_LOCATION_SUMMARY__BUILD);

    RENAME TABLE
        HOST_LOCATION_SUMMARY TO HOST_LOCATION_SUMMARY__OLD,
        HOST_LOCATION_SUMMARY__BUILD TO HOST_LOCATION_SUMMARY;
    DROP TABLE HOST_LOCATION_SUMMARY__OLD;

    UPDATE SUMMARY_REFRESH_STATE
    SET
        DT_LAST_END = UTC_TIMESTAMP(),
        IS_SUCCESS = 1,
        NU_LAST_ROW_COUNT = v_row_count,
        NA_SOURCE_HIGH_WATERMARK = CONCAT(
            'links=',
            (SELECT COUNT(*) FROM HOST_EQUIPMENT_LINK WHERE IS_ACTIVE = 1),
            ';site_obs=',
            (SELECT COUNT(*) FROM SITE_EQUIPMENT_OBS_SUMMARY)
        ),
        NA_ERROR_MESSAGE = NULL
    WHERE NA_OBJECT_NAME = 'HOST_LOCATION_SUMMARY';

    INSERT INTO SUMMARY_REFRESH_LOG (
        NA_OBJECT_NAME,
        DT_STARTED_AT,
        DT_FINISHED_AT,
        IS_SUCCESS,
        NU_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        'HOST_LOCATION_SUMMARY',
        v_started_at,
        UTC_TIMESTAMP(),
        1,
        v_row_count,
        CONCAT(
            'links=',
            (SELECT COUNT(*) FROM HOST_EQUIPMENT_LINK WHERE IS_ACTIVE = 1),
            ';site_obs=',
            (SELECT COUNT(*) FROM SITE_EQUIPMENT_OBS_SUMMARY)
        ),
        NULL
    );
END$$

CREATE PROCEDURE `PRC_REFRESH_MAP_SITE_STATION_SUMMARY_FULL`()
BEGIN
    DECLARE v_started_at DATETIME DEFAULT UTC_TIMESTAMP();
    DECLARE v_row_count BIGINT DEFAULT 0;

    INSERT INTO SUMMARY_REFRESH_STATE (
        NA_OBJECT_NAME,
        DT_LAST_START,
        DT_LAST_END,
        IS_SUCCESS,
        NU_LAST_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES ('MAP_SITE_STATION_SUMMARY', v_started_at, NULL, 0, NULL, NULL, NULL)
    ON DUPLICATE KEY UPDATE
        DT_LAST_START = VALUES(DT_LAST_START),
        DT_LAST_END = VALUES(DT_LAST_END),
        IS_SUCCESS = VALUES(IS_SUCCESS),
        NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
        NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
        NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

    DROP TABLE IF EXISTS MAP_SITE_STATION_SUMMARY__BUILD;
    DROP TABLE IF EXISTS MAP_SITE_STATION_SUMMARY__OLD;
    CREATE TABLE MAP_SITE_STATION_SUMMARY__BUILD LIKE MAP_SITE_STATION_SUMMARY;

    INSERT INTO MAP_SITE_STATION_SUMMARY__BUILD (
        FK_SITE,
        FK_EQUIPMENT,
        FK_HOST,
        NA_SITE_LABEL,
        NA_EQUIPMENT,
        NA_HOST_NAME,
        IS_OFFLINE,
        IS_CURRENT_LOCATION,
        NA_MAP_STATE,
        NU_STATE_PRIORITY,
        DT_FIRST_SEEN_AT,
        DT_LAST_SEEN_AT,
        NU_SPECTRUM_COUNT,
        NA_MATCH_TYPE,
        VL_MATCH_CONFIDENCE,
        DT_REFRESHED_AT
    )
    SELECT
        obs.FK_SITE,
        obs.FK_EQUIPMENT,
        link.FK_HOST,
        obs.NA_SITE_LABEL,
        obs.NA_EQUIPMENT,
        host.NA_HOST_NAME,
        host.IS_OFFLINE,
        obs.IS_CURRENT_LOCATION,
        FN_SUMMARY_MAP_STATE(
            CASE WHEN link.FK_HOST IS NULL THEN 0 ELSE 1 END,
            host.IS_OFFLINE,
            obs.IS_CURRENT_LOCATION
        ) AS NA_MAP_STATE,
        FN_SUMMARY_MAP_STATE_PRIORITY(
            FN_SUMMARY_MAP_STATE(
                CASE WHEN link.FK_HOST IS NULL THEN 0 ELSE 1 END,
                host.IS_OFFLINE,
                obs.IS_CURRENT_LOCATION
            )
        ) AS NU_STATE_PRIORITY,
        obs.DT_FIRST_SEEN_AT,
        obs.DT_LAST_SEEN_AT,
        obs.NU_SPECTRUM_COUNT,
        link.NA_MATCH_TYPE,
        link.VL_MATCH_CONFIDENCE,
        UTC_TIMESTAMP()
    FROM SITE_EQUIPMENT_OBS_SUMMARY obs
    LEFT JOIN HOST_EQUIPMENT_LINK link
      ON link.FK_EQUIPMENT = obs.FK_EQUIPMENT
     AND link.IS_ACTIVE = 1
     AND link.IS_PRIMARY_LINK = 1
    LEFT JOIN BPDATA.HOST host
      ON host.ID_HOST = link.FK_HOST;

    SET v_row_count = (SELECT COUNT(*) FROM MAP_SITE_STATION_SUMMARY__BUILD);

    RENAME TABLE
        MAP_SITE_STATION_SUMMARY TO MAP_SITE_STATION_SUMMARY__OLD,
        MAP_SITE_STATION_SUMMARY__BUILD TO MAP_SITE_STATION_SUMMARY;
    DROP TABLE MAP_SITE_STATION_SUMMARY__OLD;

    UPDATE SUMMARY_REFRESH_STATE
    SET
        DT_LAST_END = UTC_TIMESTAMP(),
        IS_SUCCESS = 1,
        NU_LAST_ROW_COUNT = v_row_count,
        NA_SOURCE_HIGH_WATERMARK = CONCAT(
            'site_obs=',
            (SELECT COUNT(*) FROM SITE_EQUIPMENT_OBS_SUMMARY),
            ';links=',
            (SELECT COUNT(*) FROM HOST_EQUIPMENT_LINK WHERE IS_ACTIVE = 1 AND IS_PRIMARY_LINK = 1)
        ),
        NA_ERROR_MESSAGE = NULL
    WHERE NA_OBJECT_NAME = 'MAP_SITE_STATION_SUMMARY';

    INSERT INTO SUMMARY_REFRESH_LOG (
        NA_OBJECT_NAME,
        DT_STARTED_AT,
        DT_FINISHED_AT,
        IS_SUCCESS,
        NU_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        'MAP_SITE_STATION_SUMMARY',
        v_started_at,
        UTC_TIMESTAMP(),
        1,
        v_row_count,
        CONCAT(
            'site_obs=',
            (SELECT COUNT(*) FROM SITE_EQUIPMENT_OBS_SUMMARY),
            ';links=',
            (SELECT COUNT(*) FROM HOST_EQUIPMENT_LINK WHERE IS_ACTIVE = 1 AND IS_PRIMARY_LINK = 1)
        ),
        NULL
    );
END$$

CREATE PROCEDURE `PRC_REFRESH_MAP_SITE_SUMMARY_FULL`()
BEGIN
    DECLARE v_started_at DATETIME DEFAULT UTC_TIMESTAMP();
    DECLARE v_row_count BIGINT DEFAULT 0;

    INSERT INTO SUMMARY_REFRESH_STATE (
        NA_OBJECT_NAME,
        DT_LAST_START,
        DT_LAST_END,
        IS_SUCCESS,
        NU_LAST_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES ('MAP_SITE_SUMMARY', v_started_at, NULL, 0, NULL, NULL, NULL)
    ON DUPLICATE KEY UPDATE
        DT_LAST_START = VALUES(DT_LAST_START),
        DT_LAST_END = VALUES(DT_LAST_END),
        IS_SUCCESS = VALUES(IS_SUCCESS),
        NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
        NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
        NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

    DROP TABLE IF EXISTS MAP_SITE_SUMMARY__BUILD;
    DROP TABLE IF EXISTS MAP_SITE_SUMMARY__OLD;
    CREATE TABLE MAP_SITE_SUMMARY__BUILD LIKE MAP_SITE_SUMMARY;

    INSERT INTO MAP_SITE_SUMMARY__BUILD (
        FK_SITE,
        NA_SITE_LABEL,
        FK_COUNTY,
        FK_DISTRICT,
        NA_COUNTY_NAME,
        NA_DISTRICT_NAME,
        ID_STATE,
        NA_STATE_NAME,
        NA_STATE_CODE,
        VL_LATITUDE,
        VL_LONGITUDE,
        VL_ALTITUDE,
        NU_GNSS_MEASUREMENTS,
        NA_MARKER_STATE,
        NU_STATION_COUNT,
        NU_KNOWN_HOST_COUNT,
        NU_ONLINE_CURRENT_COUNT,
        NU_ONLINE_PREVIOUS_COUNT,
        NU_OFFLINE_CURRENT_COUNT,
        NU_OFFLINE_PREVIOUS_COUNT,
        NU_NO_HOST_COUNT,
        HAS_ONLINE_STATION,
        HAS_ONLINE_HOST,
        HAS_KNOWN_HOST,
        DT_REFRESHED_AT
    )
    SELECT
        s.ID_SITE,
        COALESCE(NULLIF(s.NA_SITE, ''), CONCAT('Site ', s.ID_SITE)) AS NA_SITE_LABEL,
        s.FK_COUNTY,
        s.FK_DISTRICT,
        c.NA_COUNTY,
        d.NA_DISTRICT,
        st.ID_STATE,
        st.NA_STATE,
        st.LC_STATE,
        ST_Y(s.GEO_POINT) AS VL_LATITUDE,
        ST_X(s.GEO_POINT) AS VL_LONGITUDE,
        s.NU_ALTITUDE,
        s.NU_GNSS_MEASUREMENTS,
        CASE
            WHEN agg.MIN_PRIORITY = 0 THEN 'online_current'
            WHEN agg.MIN_PRIORITY = 1 THEN 'online_previous'
            WHEN agg.MIN_PRIORITY = 2 THEN 'offline_current'
            WHEN agg.MIN_PRIORITY = 3 THEN 'offline_previous'
            ELSE 'no_host'
        END AS NA_MARKER_STATE,
        COALESCE(agg.NU_STATION_COUNT, 0),
        COALESCE(agg.NU_KNOWN_HOST_COUNT, 0),
        COALESCE(agg.NU_ONLINE_CURRENT_COUNT, 0),
        COALESCE(agg.NU_ONLINE_PREVIOUS_COUNT, 0),
        COALESCE(agg.NU_OFFLINE_CURRENT_COUNT, 0),
        COALESCE(agg.NU_OFFLINE_PREVIOUS_COUNT, 0),
        COALESCE(agg.NU_NO_HOST_COUNT, 0),
        CASE WHEN COALESCE(agg.NU_ONLINE_CURRENT_COUNT, 0) + COALESCE(agg.NU_ONLINE_PREVIOUS_COUNT, 0) > 0 THEN 1 ELSE 0 END,
        CASE WHEN COALESCE(agg.NU_ONLINE_CURRENT_COUNT, 0) + COALESCE(agg.NU_ONLINE_PREVIOUS_COUNT, 0) > 0 THEN 1 ELSE 0 END,
        CASE WHEN COALESCE(agg.NU_KNOWN_HOST_COUNT, 0) > 0 THEN 1 ELSE 0 END,
        UTC_TIMESTAMP()
    FROM RFDATA.DIM_SPECTRUM_SITE s
    LEFT JOIN RFDATA.DIM_SITE_COUNTY c
      ON c.ID_COUNTY = s.FK_COUNTY
    LEFT JOIN RFDATA.DIM_SITE_DISTRICT d
      ON d.ID_DISTRICT = s.FK_DISTRICT
    LEFT JOIN RFDATA.DIM_SITE_STATE st
      ON st.ID_STATE = s.FK_STATE
    LEFT JOIN (
        SELECT
            ms.FK_SITE,
            COUNT(*) AS NU_STATION_COUNT,
            SUM(CASE WHEN ms.FK_HOST IS NOT NULL THEN 1 ELSE 0 END) AS NU_KNOWN_HOST_COUNT,
            SUM(CASE WHEN ms.NA_MAP_STATE = 'online_current' THEN 1 ELSE 0 END) AS NU_ONLINE_CURRENT_COUNT,
            SUM(CASE WHEN ms.NA_MAP_STATE = 'online_previous' THEN 1 ELSE 0 END) AS NU_ONLINE_PREVIOUS_COUNT,
            SUM(CASE WHEN ms.NA_MAP_STATE = 'offline_current' THEN 1 ELSE 0 END) AS NU_OFFLINE_CURRENT_COUNT,
            SUM(CASE WHEN ms.NA_MAP_STATE = 'offline_previous' THEN 1 ELSE 0 END) AS NU_OFFLINE_PREVIOUS_COUNT,
            SUM(CASE WHEN ms.NA_MAP_STATE = 'no_host' THEN 1 ELSE 0 END) AS NU_NO_HOST_COUNT,
            MIN(ms.NU_STATE_PRIORITY) AS MIN_PRIORITY
        FROM MAP_SITE_STATION_SUMMARY ms
        GROUP BY ms.FK_SITE
    ) agg
      ON agg.FK_SITE = s.ID_SITE
    WHERE s.GEO_POINT IS NOT NULL;

    SET v_row_count = (SELECT COUNT(*) FROM MAP_SITE_SUMMARY__BUILD);

    RENAME TABLE
        MAP_SITE_SUMMARY TO MAP_SITE_SUMMARY__OLD,
        MAP_SITE_SUMMARY__BUILD TO MAP_SITE_SUMMARY;
    DROP TABLE MAP_SITE_SUMMARY__OLD;

    UPDATE SUMMARY_REFRESH_STATE
    SET
        DT_LAST_END = UTC_TIMESTAMP(),
        IS_SUCCESS = 1,
        NU_LAST_ROW_COUNT = v_row_count,
        NA_SOURCE_HIGH_WATERMARK = CONCAT(
            'sites=',
            (SELECT COUNT(*) FROM RFDATA.DIM_SPECTRUM_SITE WHERE GEO_POINT IS NOT NULL),
            ';map_site_station=',
            (SELECT COUNT(*) FROM MAP_SITE_STATION_SUMMARY)
        ),
        NA_ERROR_MESSAGE = NULL
    WHERE NA_OBJECT_NAME = 'MAP_SITE_SUMMARY';

    INSERT INTO SUMMARY_REFRESH_LOG (
        NA_OBJECT_NAME,
        DT_STARTED_AT,
        DT_FINISHED_AT,
        IS_SUCCESS,
        NU_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        'MAP_SITE_SUMMARY',
        v_started_at,
        UTC_TIMESTAMP(),
        1,
        v_row_count,
        CONCAT(
            'sites=',
            (SELECT COUNT(*) FROM RFDATA.DIM_SPECTRUM_SITE WHERE GEO_POINT IS NOT NULL),
            ';map_site_station=',
            (SELECT COUNT(*) FROM MAP_SITE_STATION_SUMMARY)
        ),
        NULL
    );
END$$

CREATE PROCEDURE `PRC_REFRESH_HOST_MONTHLY_METRIC_FULL`()
BEGIN
    DECLARE v_started_at DATETIME DEFAULT UTC_TIMESTAMP();
    DECLARE v_row_count BIGINT DEFAULT 0;

    INSERT INTO SUMMARY_REFRESH_STATE (
        NA_OBJECT_NAME,
        DT_LAST_START,
        DT_LAST_END,
        IS_SUCCESS,
        NU_LAST_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES ('HOST_MONTHLY_METRIC', v_started_at, NULL, 0, NULL, NULL, NULL)
    ON DUPLICATE KEY UPDATE
        DT_LAST_START = VALUES(DT_LAST_START),
        DT_LAST_END = VALUES(DT_LAST_END),
        IS_SUCCESS = VALUES(IS_SUCCESS),
        NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
        NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
        NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

    TRUNCATE TABLE HOST_MONTHLY_METRIC;

    INSERT INTO HOST_MONTHLY_METRIC (
        FK_HOST,
        DT_REFERENCE_MONTH,
        NA_HOST_NAME,
        NU_DISCOVERED_FILES,
        VL_DISCOVERED_GB,
        NU_BACKUP_DONE_FILES,
        VL_BACKUP_DONE_GB,
        NU_BACKUP_PENDING_FILES,
        VL_BACKUP_PENDING_GB,
        NU_BACKUP_ERROR_FILES,
        VL_BACKUP_ERROR_GB,
        NU_PROCESSING_DONE_FILES,
        VL_PROCESSING_DONE_GB,
        NU_PROCESSING_PENDING_FILES,
        VL_PROCESSING_PENDING_GB,
        NU_PROCESSING_ERROR_FILES,
        VL_PROCESSING_ERROR_GB,
        DT_REFRESHED_AT
    )
    SELECT
        f.FK_HOST,
        STR_TO_DATE(DATE_FORMAT(f.DT_FILE_CREATED, '%Y-%m-01'), '%Y-%m-%d') AS DT_REFERENCE_MONTH,
        h.NA_HOST_NAME,
        COUNT(*) AS NU_DISCOVERED_FILES,
        ROUND(COALESCE(SUM(f.VL_FILE_SIZE_KB), 0) / 1024 / 1024, 2) AS VL_DISCOVERED_GB,
        SUM(CASE WHEN f.NU_STATUS_BACKUP = 0 THEN 1 ELSE 0 END) AS NU_BACKUP_DONE_FILES,
        ROUND(COALESCE(SUM(CASE WHEN f.NU_STATUS_BACKUP = 0 THEN f.VL_FILE_SIZE_KB ELSE 0 END), 0) / 1024 / 1024, 2) AS VL_BACKUP_DONE_GB,
        SUM(CASE WHEN f.NU_STATUS_BACKUP = 1 THEN 1 ELSE 0 END) AS NU_BACKUP_PENDING_FILES,
        ROUND(COALESCE(SUM(CASE WHEN f.NU_STATUS_BACKUP = 1 THEN f.VL_FILE_SIZE_KB ELSE 0 END), 0) / 1024 / 1024, 2) AS VL_BACKUP_PENDING_GB,
        SUM(CASE WHEN f.NU_STATUS_BACKUP = -1 THEN 1 ELSE 0 END) AS NU_BACKUP_ERROR_FILES,
        ROUND(COALESCE(SUM(CASE WHEN f.NU_STATUS_BACKUP = -1 THEN f.VL_FILE_SIZE_KB ELSE 0 END), 0) / 1024 / 1024, 2) AS VL_BACKUP_ERROR_GB,
        SUM(CASE WHEN f.NU_STATUS_PROCESSING = 0 THEN 1 ELSE 0 END) AS NU_PROCESSING_DONE_FILES,
        ROUND(COALESCE(SUM(CASE WHEN f.NU_STATUS_PROCESSING = 0 THEN f.VL_FILE_SIZE_KB ELSE 0 END), 0) / 1024 / 1024, 2) AS VL_PROCESSING_DONE_GB,
        SUM(CASE WHEN f.NU_STATUS_PROCESSING = 1 THEN 1 ELSE 0 END) AS NU_PROCESSING_PENDING_FILES,
        ROUND(COALESCE(SUM(CASE WHEN f.NU_STATUS_PROCESSING = 1 THEN f.VL_FILE_SIZE_KB ELSE 0 END), 0) / 1024 / 1024, 2) AS VL_PROCESSING_PENDING_GB,
        SUM(CASE WHEN f.NU_STATUS_PROCESSING = -1 THEN 1 ELSE 0 END) AS NU_PROCESSING_ERROR_FILES,
        ROUND(COALESCE(SUM(CASE WHEN f.NU_STATUS_PROCESSING = -1 THEN f.VL_FILE_SIZE_KB ELSE 0 END), 0) / 1024 / 1024, 2) AS VL_PROCESSING_ERROR_GB,
        UTC_TIMESTAMP()
    FROM BPDATA.FILE_TASK_HISTORY f
    JOIN BPDATA.HOST h
      ON h.ID_HOST = f.FK_HOST
    WHERE f.DT_FILE_CREATED IS NOT NULL
    GROUP BY
        f.FK_HOST,
        STR_TO_DATE(DATE_FORMAT(f.DT_FILE_CREATED, '%Y-%m-01'), '%Y-%m-%d'),
        h.NA_HOST_NAME;

    SET v_row_count = (SELECT COUNT(*) FROM HOST_MONTHLY_METRIC);

    UPDATE SUMMARY_REFRESH_STATE
    SET
        DT_LAST_END = UTC_TIMESTAMP(),
        IS_SUCCESS = 1,
        NU_LAST_ROW_COUNT = v_row_count,
        NA_SOURCE_HIGH_WATERMARK = CONCAT('max_history_id=', COALESCE((SELECT MAX(ID_HISTORY) FROM BPDATA.FILE_TASK_HISTORY), 0)),
        NA_ERROR_MESSAGE = NULL
    WHERE NA_OBJECT_NAME = 'HOST_MONTHLY_METRIC';

    INSERT INTO SUMMARY_REFRESH_LOG (
        NA_OBJECT_NAME,
        DT_STARTED_AT,
        DT_FINISHED_AT,
        IS_SUCCESS,
        NU_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        'HOST_MONTHLY_METRIC',
        v_started_at,
        UTC_TIMESTAMP(),
        1,
        v_row_count,
        CONCAT('max_history_id=', COALESCE((SELECT MAX(ID_HISTORY) FROM BPDATA.FILE_TASK_HISTORY), 0)),
        NULL
    );
END$$

CREATE PROCEDURE `PRC_REFRESH_HOST_ERROR_SUMMARY_FULL`()
BEGIN
    DECLARE v_started_at DATETIME DEFAULT UTC_TIMESTAMP();
    DECLARE v_row_count BIGINT DEFAULT 0;

    INSERT INTO SUMMARY_REFRESH_STATE (
        NA_OBJECT_NAME,
        DT_LAST_START,
        DT_LAST_END,
        IS_SUCCESS,
        NU_LAST_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES ('HOST_ERROR_SUMMARY', v_started_at, NULL, 0, NULL, NULL, NULL)
    ON DUPLICATE KEY UPDATE
        DT_LAST_START = VALUES(DT_LAST_START),
        DT_LAST_END = VALUES(DT_LAST_END),
        IS_SUCCESS = VALUES(IS_SUCCESS),
        NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
        NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
        NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

    DROP TABLE IF EXISTS HOST_ERROR_SUMMARY__BUILD;
    DROP TABLE IF EXISTS HOST_ERROR_SUMMARY__OLD;
    CREATE TABLE HOST_ERROR_SUMMARY__BUILD LIKE HOST_ERROR_SUMMARY;

    INSERT INTO HOST_ERROR_SUMMARY__BUILD (
        FK_HOST,
        NA_HOST_NAME,
        NA_ERROR_SCOPE,
        NA_ERROR_DOMAIN,
        NA_ERROR_STAGE,
        NA_ERROR_CODE,
        NA_ERROR_SUMMARY_HASH,
        NA_ERROR_SUMMARY,
        NU_ERROR_COUNT,
        DT_FIRST_SEEN_AT,
        DT_LAST_SEEN_AT,
        NA_LAST_SOURCE_TABLE,
        ID_LAST_SOURCE_ROW,
        NA_LAST_ERROR_DETAIL,
        NA_LAST_RAW_MESSAGE,
        DT_REFRESHED_AT
    )
    SELECT
        grouped.FK_HOST,
        grouped.NA_HOST_NAME,
        grouped.NA_ERROR_SCOPE,
        grouped.NA_ERROR_DOMAIN,
        grouped.NA_ERROR_STAGE,
        grouped.NA_ERROR_CODE,
        grouped.NA_ERROR_SUMMARY_HASH,
        grouped.NA_ERROR_SUMMARY,
        grouped.NU_ERROR_COUNT,
        grouped.DT_FIRST_SEEN_AT,
        grouped.DT_LAST_SEEN_AT,
        last_row.NA_SOURCE_TABLE,
        last_row.ID_SOURCE_ROW,
        last_row.NA_ERROR_DETAIL,
        last_row.NA_RAW_MESSAGE,
        UTC_TIMESTAMP()
    FROM (
        SELECT
            e.FK_HOST,
            COALESCE(e.NA_HOST_NAME, CONCAT('Host ', e.FK_HOST)) AS NA_HOST_NAME,
            e.NA_ERROR_SCOPE,
            e.NA_ERROR_DOMAIN,
            e.NA_ERROR_STAGE,
            e.NA_ERROR_CODE,
            e.NA_ERROR_SUMMARY_HASH,
            e.NA_ERROR_SUMMARY,
            COUNT(*) AS NU_ERROR_COUNT,
            MIN(e.DT_EVENT_AT) AS DT_FIRST_SEEN_AT,
            MAX(e.DT_EVENT_AT) AS DT_LAST_SEEN_AT
        FROM VW_ERROR_EVENT_CANONICAL e
        WHERE e.FK_HOST IS NOT NULL
        GROUP BY
            e.FK_HOST,
            COALESCE(e.NA_HOST_NAME, CONCAT('Host ', e.FK_HOST)),
            e.NA_ERROR_SCOPE,
            e.NA_ERROR_DOMAIN,
            e.NA_ERROR_STAGE,
            e.NA_ERROR_CODE,
            e.NA_ERROR_SUMMARY_HASH,
            e.NA_ERROR_SUMMARY
    ) grouped
    LEFT JOIN (
        SELECT
            ranked.FK_HOST,
            ranked.NA_ERROR_SCOPE,
            ranked.NA_ERROR_DOMAIN,
            ranked.NA_ERROR_STAGE,
            ranked.NA_ERROR_CODE,
            ranked.NA_ERROR_SUMMARY_HASH,
            ranked.NA_SOURCE_TABLE,
            ranked.ID_SOURCE_ROW,
            ranked.NA_ERROR_DETAIL,
            ranked.NA_RAW_MESSAGE
        FROM (
            SELECT
                e.FK_HOST,
                e.NA_ERROR_SCOPE,
                e.NA_ERROR_DOMAIN,
                e.NA_ERROR_STAGE,
                e.NA_ERROR_CODE,
                e.NA_ERROR_SUMMARY_HASH,
                e.NA_SOURCE_TABLE,
                e.ID_SOURCE_ROW,
                e.NA_ERROR_DETAIL,
                e.NA_RAW_MESSAGE,
                ROW_NUMBER() OVER (
                    PARTITION BY
                        e.FK_HOST,
                        e.NA_ERROR_SCOPE,
                        e.NA_ERROR_DOMAIN,
                        e.NA_ERROR_STAGE,
                        e.NA_ERROR_CODE,
                        e.NA_ERROR_SUMMARY_HASH
                    ORDER BY
                        COALESCE(e.DT_EVENT_AT, '1970-01-01 00:00:00') DESC,
                        e.ID_SOURCE_ROW DESC
                ) AS RN_LAST
            FROM VW_ERROR_EVENT_CANONICAL e
            WHERE e.FK_HOST IS NOT NULL
        ) ranked
        WHERE ranked.RN_LAST = 1
    ) last_row
      ON grouped.FK_HOST = last_row.FK_HOST
     AND grouped.NA_ERROR_SCOPE = last_row.NA_ERROR_SCOPE
     AND grouped.NA_ERROR_DOMAIN <=> last_row.NA_ERROR_DOMAIN
     AND grouped.NA_ERROR_STAGE <=> last_row.NA_ERROR_STAGE
     AND grouped.NA_ERROR_CODE <=> last_row.NA_ERROR_CODE
     AND grouped.NA_ERROR_SUMMARY_HASH = last_row.NA_ERROR_SUMMARY_HASH;

    SET v_row_count = (SELECT COUNT(*) FROM HOST_ERROR_SUMMARY__BUILD);

    RENAME TABLE
        HOST_ERROR_SUMMARY TO HOST_ERROR_SUMMARY__OLD,
        HOST_ERROR_SUMMARY__BUILD TO HOST_ERROR_SUMMARY;
    DROP TABLE HOST_ERROR_SUMMARY__OLD;

    UPDATE SUMMARY_REFRESH_STATE
    SET
        DT_LAST_END = UTC_TIMESTAMP(),
        IS_SUCCESS = 1,
        NU_LAST_ROW_COUNT = v_row_count,
        NA_SOURCE_HIGH_WATERMARK = CONCAT(
            'max_history_id=',
            COALESCE((SELECT MAX(ID_HISTORY) FROM BPDATA.FILE_TASK_HISTORY), 0),
            ';max_file_task_id=',
            COALESCE((SELECT MAX(ID_FILE_TASK) FROM BPDATA.FILE_TASK), 0),
            ';max_host_task_id=',
            COALESCE((SELECT MAX(ID_HOST_TASK) FROM BPDATA.HOST_TASK), 0)
        ),
        NA_ERROR_MESSAGE = NULL
    WHERE NA_OBJECT_NAME = 'HOST_ERROR_SUMMARY';

    INSERT INTO SUMMARY_REFRESH_LOG (
        NA_OBJECT_NAME,
        DT_STARTED_AT,
        DT_FINISHED_AT,
        IS_SUCCESS,
        NU_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        'HOST_ERROR_SUMMARY',
        v_started_at,
        UTC_TIMESTAMP(),
        1,
        v_row_count,
        CONCAT(
            'max_history_id=',
            COALESCE((SELECT MAX(ID_HISTORY) FROM BPDATA.FILE_TASK_HISTORY), 0),
            ';max_file_task_id=',
            COALESCE((SELECT MAX(ID_FILE_TASK) FROM BPDATA.FILE_TASK), 0),
            ';max_host_task_id=',
            COALESCE((SELECT MAX(ID_HOST_TASK) FROM BPDATA.HOST_TASK), 0)
        ),
        NULL
    );
END$$

CREATE PROCEDURE `PRC_REFRESH_SERVER_ERROR_SUMMARY_FULL`()
BEGIN
    DECLARE v_started_at DATETIME DEFAULT UTC_TIMESTAMP();
    DECLARE v_row_count BIGINT DEFAULT 0;

    INSERT INTO SUMMARY_REFRESH_STATE (
        NA_OBJECT_NAME,
        DT_LAST_START,
        DT_LAST_END,
        IS_SUCCESS,
        NU_LAST_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES ('SERVER_ERROR_SUMMARY', v_started_at, NULL, 0, NULL, NULL, NULL)
    ON DUPLICATE KEY UPDATE
        DT_LAST_START = VALUES(DT_LAST_START),
        DT_LAST_END = VALUES(DT_LAST_END),
        IS_SUCCESS = VALUES(IS_SUCCESS),
        NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
        NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
        NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

    DROP TABLE IF EXISTS SERVER_ERROR_SUMMARY__BUILD;
    DROP TABLE IF EXISTS SERVER_ERROR_SUMMARY__OLD;
    CREATE TABLE SERVER_ERROR_SUMMARY__BUILD LIKE SERVER_ERROR_SUMMARY;

    INSERT INTO SERVER_ERROR_SUMMARY__BUILD (
        NA_ERROR_SCOPE,
        NA_ERROR_DOMAIN,
        NA_ERROR_STAGE,
        NA_ERROR_CODE,
        NA_ERROR_SUMMARY_HASH,
        NA_ERROR_SUMMARY,
        NU_ERROR_COUNT,
        DT_FIRST_SEEN_AT,
        DT_LAST_SEEN_AT,
        NA_LAST_SOURCE_TABLE,
        ID_LAST_SOURCE_ROW,
        NA_LAST_ERROR_DETAIL,
        NA_LAST_RAW_MESSAGE,
        DT_REFRESHED_AT
    )
    SELECT
        grouped.NA_ERROR_SCOPE,
        grouped.NA_ERROR_DOMAIN,
        grouped.NA_ERROR_STAGE,
        grouped.NA_ERROR_CODE,
        grouped.NA_ERROR_SUMMARY_HASH,
        grouped.NA_ERROR_SUMMARY,
        grouped.NU_ERROR_COUNT,
        grouped.DT_FIRST_SEEN_AT,
        grouped.DT_LAST_SEEN_AT,
        last_row.NA_SOURCE_TABLE,
        last_row.ID_SOURCE_ROW,
        last_row.NA_ERROR_DETAIL,
        last_row.NA_RAW_MESSAGE,
        UTC_TIMESTAMP()
    FROM (
        SELECT
            e.NA_ERROR_SCOPE,
            e.NA_ERROR_DOMAIN,
            e.NA_ERROR_STAGE,
            e.NA_ERROR_CODE,
            e.NA_ERROR_SUMMARY_HASH,
            e.NA_ERROR_SUMMARY,
            COUNT(*) AS NU_ERROR_COUNT,
            MIN(e.DT_EVENT_AT) AS DT_FIRST_SEEN_AT,
            MAX(e.DT_EVENT_AT) AS DT_LAST_SEEN_AT
        FROM VW_ERROR_EVENT_CANONICAL e
        GROUP BY
            e.NA_ERROR_SCOPE,
            e.NA_ERROR_DOMAIN,
            e.NA_ERROR_STAGE,
            e.NA_ERROR_CODE,
            e.NA_ERROR_SUMMARY_HASH,
            e.NA_ERROR_SUMMARY
    ) grouped
    LEFT JOIN (
        SELECT
            ranked.NA_ERROR_SCOPE,
            ranked.NA_ERROR_DOMAIN,
            ranked.NA_ERROR_STAGE,
            ranked.NA_ERROR_CODE,
            ranked.NA_ERROR_SUMMARY_HASH,
            ranked.NA_SOURCE_TABLE,
            ranked.ID_SOURCE_ROW,
            ranked.NA_ERROR_DETAIL,
            ranked.NA_RAW_MESSAGE
        FROM (
            SELECT
                e.NA_ERROR_SCOPE,
                e.NA_ERROR_DOMAIN,
                e.NA_ERROR_STAGE,
                e.NA_ERROR_CODE,
                e.NA_ERROR_SUMMARY_HASH,
                e.NA_SOURCE_TABLE,
                e.ID_SOURCE_ROW,
                e.NA_ERROR_DETAIL,
                e.NA_RAW_MESSAGE,
                ROW_NUMBER() OVER (
                    PARTITION BY
                        e.NA_ERROR_SCOPE,
                        e.NA_ERROR_DOMAIN,
                        e.NA_ERROR_STAGE,
                        e.NA_ERROR_CODE,
                        e.NA_ERROR_SUMMARY_HASH
                    ORDER BY
                        COALESCE(e.DT_EVENT_AT, '1970-01-01 00:00:00') DESC,
                        e.ID_SOURCE_ROW DESC
                ) AS RN_LAST
            FROM VW_ERROR_EVENT_CANONICAL e
        ) ranked
        WHERE ranked.RN_LAST = 1
    ) last_row
      ON grouped.NA_ERROR_SCOPE = last_row.NA_ERROR_SCOPE
     AND grouped.NA_ERROR_DOMAIN <=> last_row.NA_ERROR_DOMAIN
     AND grouped.NA_ERROR_STAGE <=> last_row.NA_ERROR_STAGE
     AND grouped.NA_ERROR_CODE <=> last_row.NA_ERROR_CODE
     AND grouped.NA_ERROR_SUMMARY_HASH = last_row.NA_ERROR_SUMMARY_HASH;

    SET v_row_count = (SELECT COUNT(*) FROM SERVER_ERROR_SUMMARY__BUILD);

    RENAME TABLE
        SERVER_ERROR_SUMMARY TO SERVER_ERROR_SUMMARY__OLD,
        SERVER_ERROR_SUMMARY__BUILD TO SERVER_ERROR_SUMMARY;
    DROP TABLE SERVER_ERROR_SUMMARY__OLD;

    UPDATE SUMMARY_REFRESH_STATE
    SET
        DT_LAST_END = UTC_TIMESTAMP(),
        IS_SUCCESS = 1,
        NU_LAST_ROW_COUNT = v_row_count,
        NA_SOURCE_HIGH_WATERMARK = CONCAT(
            'max_history_id=',
            COALESCE((SELECT MAX(ID_HISTORY) FROM BPDATA.FILE_TASK_HISTORY), 0),
            ';max_file_task_id=',
            COALESCE((SELECT MAX(ID_FILE_TASK) FROM BPDATA.FILE_TASK), 0),
            ';max_host_task_id=',
            COALESCE((SELECT MAX(ID_HOST_TASK) FROM BPDATA.HOST_TASK), 0)
        ),
        NA_ERROR_MESSAGE = NULL
    WHERE NA_OBJECT_NAME = 'SERVER_ERROR_SUMMARY';

    INSERT INTO SUMMARY_REFRESH_LOG (
        NA_OBJECT_NAME,
        DT_STARTED_AT,
        DT_FINISHED_AT,
        IS_SUCCESS,
        NU_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        'SERVER_ERROR_SUMMARY',
        v_started_at,
        UTC_TIMESTAMP(),
        1,
        v_row_count,
        CONCAT(
            'max_history_id=',
            COALESCE((SELECT MAX(ID_HISTORY) FROM BPDATA.FILE_TASK_HISTORY), 0),
            ';max_file_task_id=',
            COALESCE((SELECT MAX(ID_FILE_TASK) FROM BPDATA.FILE_TASK), 0),
            ';max_host_task_id=',
            COALESCE((SELECT MAX(ID_HOST_TASK) FROM BPDATA.HOST_TASK), 0)
        ),
        NULL
    );
END$$

CREATE PROCEDURE `PRC_REFRESH_HOST_CURRENT_SNAPSHOT_FULL`()
BEGIN
    DECLARE v_started_at DATETIME DEFAULT UTC_TIMESTAMP();
    DECLARE v_row_count BIGINT DEFAULT 0;
    DECLARE v_current_month_start DATETIME;
    DECLARE v_next_month_start DATETIME;

    SET v_current_month_start = STR_TO_DATE(DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-01 00:00:00'), '%Y-%m-%d %H:%i:%s');
    SET v_next_month_start = DATE_ADD(v_current_month_start, INTERVAL 1 MONTH);

    INSERT INTO SUMMARY_REFRESH_STATE (
        NA_OBJECT_NAME,
        DT_LAST_START,
        DT_LAST_END,
        IS_SUCCESS,
        NU_LAST_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES ('HOST_CURRENT_SNAPSHOT', v_started_at, NULL, 0, NULL, NULL, NULL)
    ON DUPLICATE KEY UPDATE
        DT_LAST_START = VALUES(DT_LAST_START),
        DT_LAST_END = VALUES(DT_LAST_END),
        IS_SUCCESS = VALUES(IS_SUCCESS),
        NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
        NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
        NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

    DROP TABLE IF EXISTS HOST_CURRENT_SNAPSHOT__BUILD;
    DROP TABLE IF EXISTS HOST_CURRENT_SNAPSHOT__OLD;
    CREATE TABLE HOST_CURRENT_SNAPSHOT__BUILD LIKE HOST_CURRENT_SNAPSHOT;

    INSERT INTO HOST_CURRENT_SNAPSHOT__BUILD (
        ID_HOST,
        NA_HOST_NAME,
        NA_HOST_ADDRESS,
        NA_HOST_PORT,
        IS_OFFLINE,
        IS_BUSY,
        NU_PID,
        DT_BUSY,
        DT_LAST_FAIL,
        DT_LAST_CHECK,
        NU_HOST_CHECK_ERROR,
        DT_LAST_DISCOVERY,
        NU_DONE_FILE_DISCOVERY_TASKS,
        NU_ERROR_FILE_DISCOVERY_TASKS,
        DT_LAST_BACKUP,
        NU_PENDING_FILE_BACKUP_TASKS,
        NU_DONE_FILE_BACKUP_TASKS,
        NU_ERROR_FILE_BACKUP_TASKS,
        NU_BACKUP_DONE_THIS_MONTH,
        VL_PENDING_BACKUP_GB,
        VL_BACKUP_DONE_GB_THIS_MONTH,
        VL_DONE_BACKUP_GB,
        DT_LAST_PROCESSING,
        NU_PENDING_FILE_PROCESS_TASKS,
        NU_DONE_FILE_PROCESS_TASKS,
        NU_ERROR_FILE_PROCESS_TASKS,
        NU_HOST_FILES,
        NU_BACKUP_QUEUE_FILES_TOTAL,
        VL_BACKUP_QUEUE_GB_TOTAL,
        NU_PROCESSING_QUEUE_FILES_TOTAL,
        VL_PROCESSING_QUEUE_GB_TOTAL,
        NU_MATCHED_EQUIPMENT_TOTAL,
        NU_FACT_SPECTRUM_TOTAL,
        FK_CURRENT_SITE,
        NA_CURRENT_SITE_LABEL,
        NA_CURRENT_STATE_CODE,
        VL_CURRENT_LATITUDE,
        VL_CURRENT_LONGITUDE,
        DT_CURRENT_SITE_LAST_SEEN,
        NA_LAST_ERROR_SCOPE,
        NA_LAST_ERROR_CODE,
        NA_LAST_ERROR_SUMMARY,
        DT_LAST_ERROR_AT,
        DT_REFRESHED_AT
    )
    SELECT
        h.ID_HOST,
        h.NA_HOST_NAME,
        h.NA_HOST_ADDRESS,
        h.NA_HOST_PORT,
        COALESCE(h.IS_OFFLINE, 0),
        COALESCE(h.IS_BUSY, 0),
        h.NU_PID,
        h.DT_BUSY,
        h.DT_LAST_FAIL,
        h.DT_LAST_CHECK,
        h.NU_HOST_CHECK_ERROR,
        h.DT_LAST_DISCOVERY,
        h.NU_DONE_FILE_DISCOVERY_TASKS,
        h.NU_ERROR_FILE_DISCOVERY_TASKS,
        h.DT_LAST_BACKUP,
        h.NU_PENDING_FILE_BACKUP_TASKS,
        h.NU_DONE_FILE_BACKUP_TASKS,
        h.NU_ERROR_FILE_BACKUP_TASKS,
        COALESCE(backup_month.NU_BACKUP_DONE_THIS_MONTH, 0),
        ROUND(COALESCE(h.VL_PENDING_BACKUP_KB, 0) / 1024 / 1024, 2),
        COALESCE(backup_month.VL_BACKUP_DONE_GB_THIS_MONTH, 0.00),
        ROUND(COALESCE(h.VL_DONE_BACKUP_KB, 0) / 1024 / 1024, 2),
        h.DT_LAST_PROCESSING,
        h.NU_PENDING_FILE_PROCESS_TASKS,
        h.NU_DONE_FILE_PROCESS_TASKS,
        h.NU_ERROR_FILE_PROCESS_TASKS,
        COALESCE(monthly_stats.NU_DISCOVERED_FILES_TOTAL, h.NU_HOST_FILES, 0),
        COALESCE(queue.NU_BACKUP_QUEUE_FILES_TOTAL, 0),
        COALESCE(queue.VL_BACKUP_QUEUE_GB_TOTAL, 0.00),
        COALESCE(queue.NU_PROCESSING_QUEUE_FILES_TOTAL, 0),
        COALESCE(queue.VL_PROCESSING_QUEUE_GB_TOTAL, 0.00),
        COALESCE(link_stats.NU_MATCHED_EQUIPMENT_TOTAL, 0),
        COALESCE(spectrum_stats.NU_FACT_SPECTRUM_TOTAL, 0),
        current_location.FK_SITE,
        current_location.NA_SITE_LABEL,
        current_location.NA_STATE_CODE,
        current_location.VL_LATITUDE,
        current_location.VL_LONGITUDE,
        current_location.DT_LAST_SEEN_AT,
        last_error.NA_ERROR_SCOPE,
        last_error.NA_ERROR_CODE,
        last_error.NA_ERROR_SUMMARY,
        last_error.DT_EVENT_AT,
        UTC_TIMESTAMP()
    FROM BPDATA.HOST h
    LEFT JOIN (
        SELECT
            t.FK_HOST,
            SUM(CASE WHEN t.NU_TYPE = 1 AND t.NU_STATUS = 1 THEN 1 ELSE 0 END) AS NU_BACKUP_QUEUE_FILES_TOTAL,
            ROUND(
                COALESCE(SUM(CASE WHEN t.NU_TYPE = 1 AND t.NU_STATUS = 1 THEN t.VL_FILE_SIZE_KB ELSE 0 END), 0)
                / 1024 / 1024,
                2
            ) AS VL_BACKUP_QUEUE_GB_TOTAL,
            SUM(CASE WHEN t.NU_TYPE = 2 AND t.NU_STATUS = 1 THEN 1 ELSE 0 END) AS NU_PROCESSING_QUEUE_FILES_TOTAL,
            ROUND(
                COALESCE(SUM(CASE WHEN t.NU_TYPE = 2 AND t.NU_STATUS = 1 THEN t.VL_FILE_SIZE_KB ELSE 0 END), 0)
                / 1024 / 1024,
                2
            ) AS VL_PROCESSING_QUEUE_GB_TOTAL
        FROM BPDATA.FILE_TASK t
        GROUP BY t.FK_HOST
    ) queue
      ON queue.FK_HOST = h.ID_HOST
    LEFT JOIN (
        SELECT
            f.FK_HOST,
            COUNT(*) AS NU_BACKUP_DONE_THIS_MONTH,
            ROUND(COALESCE(SUM(f.VL_FILE_SIZE_KB), 0) / 1024 / 1024, 2) AS VL_BACKUP_DONE_GB_THIS_MONTH
        FROM BPDATA.FILE_TASK_HISTORY f
        WHERE f.NU_STATUS_BACKUP = 0
          AND f.DT_BACKUP >= v_current_month_start
          AND f.DT_BACKUP < v_next_month_start
        GROUP BY f.FK_HOST
    ) backup_month
      ON backup_month.FK_HOST = h.ID_HOST
    LEFT JOIN (
        SELECT
            metric.FK_HOST,
            SUM(metric.NU_DISCOVERED_FILES) AS NU_DISCOVERED_FILES_TOTAL
        FROM HOST_MONTHLY_METRIC metric
        GROUP BY metric.FK_HOST
    ) monthly_stats
      ON monthly_stats.FK_HOST = h.ID_HOST
    LEFT JOIN (
        SELECT
            l.FK_HOST,
            COUNT(*) AS NU_MATCHED_EQUIPMENT_TOTAL
        FROM HOST_EQUIPMENT_LINK l
        WHERE l.IS_ACTIVE = 1
          AND l.IS_PRIMARY_LINK = 1
        GROUP BY l.FK_HOST
    ) link_stats
      ON link_stats.FK_HOST = h.ID_HOST
    LEFT JOIN (
        SELECT
            l.FK_HOST,
            SUM(obs.NU_SPECTRUM_COUNT) AS NU_FACT_SPECTRUM_TOTAL
        FROM HOST_EQUIPMENT_LINK l
        JOIN SITE_EQUIPMENT_OBS_SUMMARY obs
          ON obs.FK_EQUIPMENT = l.FK_EQUIPMENT
        WHERE l.IS_ACTIVE = 1
          AND l.IS_PRIMARY_LINK = 1
        GROUP BY l.FK_HOST
    ) spectrum_stats
      ON spectrum_stats.FK_HOST = h.ID_HOST
    LEFT JOIN (
        SELECT *
        FROM (
            SELECT
                loc.*,
                ROW_NUMBER() OVER (
                    PARTITION BY loc.FK_HOST
                    ORDER BY loc.IS_CURRENT_LOCATION DESC,
                             COALESCE(loc.DT_LAST_SEEN_AT, loc.DT_FIRST_SEEN_AT) DESC,
                             loc.FK_SITE DESC
                ) AS RN_LOCATION
            FROM HOST_LOCATION_SUMMARY loc
            WHERE loc.IS_CURRENT_LOCATION = 1
        ) ranked_loc
        WHERE ranked_loc.RN_LOCATION = 1
    ) current_location
      ON current_location.FK_HOST = h.ID_HOST
    LEFT JOIN (
        SELECT
            ranked_error.FK_HOST,
            ranked_error.NA_ERROR_SCOPE,
            ranked_error.NA_ERROR_CODE,
            ranked_error.NA_ERROR_SUMMARY,
            ranked_error.DT_EVENT_AT
        FROM (
            SELECT
                e.FK_HOST,
                e.NA_ERROR_SCOPE,
                e.NA_ERROR_CODE,
                e.NA_ERROR_SUMMARY,
                e.DT_EVENT_AT,
                e.ID_SOURCE_ROW,
                ROW_NUMBER() OVER (
                    PARTITION BY e.FK_HOST
                    ORDER BY
                        COALESCE(e.DT_EVENT_AT, '1970-01-01 00:00:00') DESC,
                        e.ID_SOURCE_ROW DESC
                ) AS RN_ERROR
            FROM VW_ERROR_EVENT_CANONICAL e
            WHERE e.FK_HOST IS NOT NULL
        ) ranked_error
        WHERE ranked_error.RN_ERROR = 1
    ) last_error
      ON last_error.FK_HOST = h.ID_HOST;

    SET v_row_count = (SELECT COUNT(*) FROM HOST_CURRENT_SNAPSHOT__BUILD);

    RENAME TABLE
        HOST_CURRENT_SNAPSHOT TO HOST_CURRENT_SNAPSHOT__OLD,
        HOST_CURRENT_SNAPSHOT__BUILD TO HOST_CURRENT_SNAPSHOT;
    DROP TABLE HOST_CURRENT_SNAPSHOT__OLD;

    UPDATE SUMMARY_REFRESH_STATE
    SET
        DT_LAST_END = UTC_TIMESTAMP(),
        IS_SUCCESS = 1,
        NU_LAST_ROW_COUNT = v_row_count,
        NA_SOURCE_HIGH_WATERMARK = CONCAT(
            'hosts=',
            (SELECT COUNT(*) FROM BPDATA.HOST),
            ';current_month=',
            DATE_FORMAT(v_current_month_start, '%Y-%m')
        ),
        NA_ERROR_MESSAGE = NULL
    WHERE NA_OBJECT_NAME = 'HOST_CURRENT_SNAPSHOT';

    INSERT INTO SUMMARY_REFRESH_LOG (
        NA_OBJECT_NAME,
        DT_STARTED_AT,
        DT_FINISHED_AT,
        IS_SUCCESS,
        NU_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        'HOST_CURRENT_SNAPSHOT',
        v_started_at,
        UTC_TIMESTAMP(),
        1,
        v_row_count,
        CONCAT(
            'hosts=',
            (SELECT COUNT(*) FROM BPDATA.HOST),
            ';current_month=',
            DATE_FORMAT(v_current_month_start, '%Y-%m')
        ),
        NULL
    );
END$$

CREATE PROCEDURE `PRC_REFRESH_SERVER_CURRENT_SUMMARY_FULL`()
BEGIN
    DECLARE v_started_at DATETIME DEFAULT UTC_TIMESTAMP();
    DECLARE v_row_count BIGINT DEFAULT 0;
    DECLARE v_current_month_start DATETIME;

    SET v_current_month_start = STR_TO_DATE(DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-01 00:00:00'), '%Y-%m-%d %H:%i:%s');

    INSERT INTO SUMMARY_REFRESH_STATE (
        NA_OBJECT_NAME,
        DT_LAST_START,
        DT_LAST_END,
        IS_SUCCESS,
        NU_LAST_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES ('SERVER_CURRENT_SUMMARY', v_started_at, NULL, 0, NULL, NULL, NULL)
    ON DUPLICATE KEY UPDATE
        DT_LAST_START = VALUES(DT_LAST_START),
        DT_LAST_END = VALUES(DT_LAST_END),
        IS_SUCCESS = VALUES(IS_SUCCESS),
        NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
        NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
        NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

    DROP TABLE IF EXISTS SERVER_CURRENT_SUMMARY__BUILD;
    DROP TABLE IF EXISTS SERVER_CURRENT_SUMMARY__OLD;
    CREATE TABLE SERVER_CURRENT_SUMMARY__BUILD LIKE SERVER_CURRENT_SUMMARY;

    INSERT INTO SERVER_CURRENT_SUMMARY__BUILD (
        ID_SUMMARY,
        NA_CURRENT_MONTH_LABEL,
        NU_TOTAL_HOSTS,
        NU_ONLINE_HOSTS,
        NU_OFFLINE_HOSTS,
        NU_BUSY_HOSTS,
        NU_DISCOVERED_FILES_TOTAL,
        NU_BACKUP_PENDING_FILES_TOTAL,
        VL_BACKUP_PENDING_GB_TOTAL,
        NU_BACKUP_ERROR_FILES_TOTAL,
        NU_BACKUP_QUEUE_FILES_TOTAL,
        VL_BACKUP_QUEUE_GB_TOTAL,
        NU_PROCESSING_PENDING_FILES_TOTAL,
        NU_PROCESSING_DONE_FILES_TOTAL,
        NU_PROCESSING_ERROR_FILES_TOTAL,
        NU_PROCESSING_QUEUE_FILES_TOTAL,
        VL_PROCESSING_QUEUE_GB_TOTAL,
        NU_FACT_SPECTRUM_TOTAL,
        NU_BACKUP_DONE_THIS_MONTH,
        VL_BACKUP_DONE_GB_THIS_MONTH,
        NU_BACKUP_ERROR_GROUPS,
        NU_PROCESSING_ERROR_GROUPS,
        DT_REFRESHED_AT
    )
    SELECT
        1,
        DATE_FORMAT(v_current_month_start, '%Y-%m'),
        COUNT(*) AS NU_TOTAL_HOSTS,
        SUM(CASE WHEN snap.IS_OFFLINE = 0 THEN 1 ELSE 0 END) AS NU_ONLINE_HOSTS,
        SUM(CASE WHEN snap.IS_OFFLINE = 1 THEN 1 ELSE 0 END) AS NU_OFFLINE_HOSTS,
        SUM(CASE WHEN snap.IS_BUSY = 1 THEN 1 ELSE 0 END) AS NU_BUSY_HOSTS,
        COALESCE(SUM(snap.NU_HOST_FILES), 0) AS NU_DISCOVERED_FILES_TOTAL,
        COALESCE(SUM(snap.NU_PENDING_FILE_BACKUP_TASKS), 0) AS NU_BACKUP_PENDING_FILES_TOTAL,
        ROUND(COALESCE(SUM(snap.VL_PENDING_BACKUP_GB), 0), 2) AS VL_BACKUP_PENDING_GB_TOTAL,
        COALESCE(SUM(snap.NU_ERROR_FILE_BACKUP_TASKS), 0) AS NU_BACKUP_ERROR_FILES_TOTAL,
        COALESCE(SUM(snap.NU_BACKUP_QUEUE_FILES_TOTAL), 0) AS NU_BACKUP_QUEUE_FILES_TOTAL,
        ROUND(COALESCE(SUM(snap.VL_BACKUP_QUEUE_GB_TOTAL), 0), 2) AS VL_BACKUP_QUEUE_GB_TOTAL,
        COALESCE(SUM(snap.NU_PENDING_FILE_PROCESS_TASKS), 0) AS NU_PROCESSING_PENDING_FILES_TOTAL,
        COALESCE(SUM(snap.NU_DONE_FILE_PROCESS_TASKS), 0) AS NU_PROCESSING_DONE_FILES_TOTAL,
        COALESCE(SUM(snap.NU_ERROR_FILE_PROCESS_TASKS), 0) AS NU_PROCESSING_ERROR_FILES_TOTAL,
        COALESCE(SUM(snap.NU_PROCESSING_QUEUE_FILES_TOTAL), 0) AS NU_PROCESSING_QUEUE_FILES_TOTAL,
        ROUND(COALESCE(SUM(snap.VL_PROCESSING_QUEUE_GB_TOTAL), 0), 2) AS VL_PROCESSING_QUEUE_GB_TOTAL,
        COALESCE(SUM(snap.NU_FACT_SPECTRUM_TOTAL), 0) AS NU_FACT_SPECTRUM_TOTAL,
        COALESCE(SUM(snap.NU_BACKUP_DONE_THIS_MONTH), 0) AS NU_BACKUP_DONE_THIS_MONTH,
        ROUND(COALESCE(SUM(snap.VL_BACKUP_DONE_GB_THIS_MONTH), 0), 2) AS VL_BACKUP_DONE_GB_THIS_MONTH,
        COALESCE((
            SELECT COUNT(*)
            FROM SERVER_ERROR_SUMMARY se
            WHERE se.NA_ERROR_SCOPE = 'BACKUP'
        ), 0) AS NU_BACKUP_ERROR_GROUPS,
        COALESCE((
            SELECT COUNT(*)
            FROM SERVER_ERROR_SUMMARY se
            WHERE se.NA_ERROR_SCOPE = 'PROCESSING'
        ), 0) AS NU_PROCESSING_ERROR_GROUPS,
        UTC_TIMESTAMP()
    FROM HOST_CURRENT_SNAPSHOT snap;

    SET v_row_count = (SELECT COUNT(*) FROM SERVER_CURRENT_SUMMARY__BUILD);

    RENAME TABLE
        SERVER_CURRENT_SUMMARY TO SERVER_CURRENT_SUMMARY__OLD,
        SERVER_CURRENT_SUMMARY__BUILD TO SERVER_CURRENT_SUMMARY;
    DROP TABLE SERVER_CURRENT_SUMMARY__OLD;

    UPDATE SUMMARY_REFRESH_STATE
    SET
        DT_LAST_END = UTC_TIMESTAMP(),
        IS_SUCCESS = 1,
        NU_LAST_ROW_COUNT = v_row_count,
        NA_SOURCE_HIGH_WATERMARK = CONCAT(
            'current_month=',
            DATE_FORMAT(v_current_month_start, '%Y-%m'),
            ';hosts=',
            (SELECT COUNT(*) FROM HOST_CURRENT_SNAPSHOT)
        ),
        NA_ERROR_MESSAGE = NULL
    WHERE NA_OBJECT_NAME = 'SERVER_CURRENT_SUMMARY';

    INSERT INTO SUMMARY_REFRESH_LOG (
        NA_OBJECT_NAME,
        DT_STARTED_AT,
        DT_FINISHED_AT,
        IS_SUCCESS,
        NU_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        'SERVER_CURRENT_SUMMARY',
        v_started_at,
        UTC_TIMESTAMP(),
        1,
        v_row_count,
        CONCAT(
            'current_month=',
            DATE_FORMAT(v_current_month_start, '%Y-%m'),
            ';hosts=',
            (SELECT COUNT(*) FROM HOST_CURRENT_SNAPSHOT)
        ),
        NULL
    );
END$$

CREATE PROCEDURE `PRC_REFRESH_ALL_RFFUSION_SUMMARY_FULL`()
BEGIN
    CALL PRC_REFRESH_HOST_EQUIPMENT_LINK_FULL();
    CALL PRC_REFRESH_SITE_EQUIPMENT_OBS_SUMMARY_FULL();
    CALL PRC_REFRESH_HOST_LOCATION_SUMMARY_FULL();
    CALL PRC_REFRESH_MAP_SITE_STATION_SUMMARY_FULL();
    CALL PRC_REFRESH_MAP_SITE_SUMMARY_FULL();
    CALL PRC_REFRESH_HOST_MONTHLY_METRIC_FULL();
    CALL PRC_REFRESH_HOST_ERROR_SUMMARY_FULL();
    CALL PRC_REFRESH_SERVER_ERROR_SUMMARY_FULL();
    CALL PRC_REFRESH_HOST_CURRENT_SNAPSHOT_FULL();
    CALL PRC_REFRESH_SERVER_CURRENT_SUMMARY_FULL();
END$$

CREATE PROCEDURE `PRC_REFRESH_ALL_RFFUSION_SUMMARY_SAFE`()
BEGIN
    DECLARE v_started_at DATETIME DEFAULT UTC_TIMESTAMP();
    DECLARE v_finished_at DATETIME DEFAULT NULL;
    DECLARE v_lock_acquired INT DEFAULT 0;
    DECLARE v_lock_status VARCHAR(16) DEFAULT 'pending';
    DECLARE v_log_object_name VARCHAR(100) DEFAULT 'RFFUSION_SUMMARY_EVENT_10MIN';
    DECLARE v_high_watermark VARCHAR(255) DEFAULT 'interval=10m';
    DECLARE v_sqlstate CHAR(5) DEFAULT NULL;
    DECLARE v_error_message TEXT DEFAULT NULL;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1
            v_sqlstate = RETURNED_SQLSTATE,
            v_error_message = MESSAGE_TEXT;

        SET v_finished_at = UTC_TIMESTAMP();

        IF v_lock_acquired = 1 THEN
            SET v_lock_status = 'acquired';
            DO RELEASE_LOCK('RFFUSION_SUMMARY_REFRESH_LOCK');
        ELSEIF v_lock_acquired = 0 THEN
            SET v_lock_status = 'pending';
        ELSE
            SET v_lock_status = 'unknown';
        END IF;

        INSERT INTO SUMMARY_REFRESH_STATE (
            NA_OBJECT_NAME,
            DT_LAST_START,
            DT_LAST_END,
            IS_SUCCESS,
            NU_LAST_ROW_COUNT,
            NA_SOURCE_HIGH_WATERMARK,
            NA_ERROR_MESSAGE
        )
        VALUES (
            v_log_object_name,
            v_started_at,
            v_finished_at,
            0,
            NULL,
            CONCAT(v_high_watermark, ';lock=', v_lock_status),
            CONCAT(
                'sqlstate=',
                COALESCE(v_sqlstate, '00000'),
                '; ',
                COALESCE(v_error_message, 'scheduled refresh failed')
            )
        )
        ON DUPLICATE KEY UPDATE
            DT_LAST_START = VALUES(DT_LAST_START),
            DT_LAST_END = VALUES(DT_LAST_END),
            IS_SUCCESS = VALUES(IS_SUCCESS),
            NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
            NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
            NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

        INSERT INTO SUMMARY_REFRESH_LOG (
            NA_OBJECT_NAME,
            DT_STARTED_AT,
            DT_FINISHED_AT,
            IS_SUCCESS,
            NU_ROW_COUNT,
            NA_SOURCE_HIGH_WATERMARK,
            NA_ERROR_MESSAGE
        )
        VALUES (
            v_log_object_name,
            v_started_at,
            v_finished_at,
            0,
            NULL,
            CONCAT(v_high_watermark, ';lock=', v_lock_status),
            CONCAT(
                'sqlstate=',
                COALESCE(v_sqlstate, '00000'),
                '; ',
                COALESCE(v_error_message, 'scheduled refresh failed')
            )
        );

        RESIGNAL;
    END;

    INSERT INTO SUMMARY_REFRESH_STATE (
        NA_OBJECT_NAME,
        DT_LAST_START,
        DT_LAST_END,
        IS_SUCCESS,
        NU_LAST_ROW_COUNT,
        NA_SOURCE_HIGH_WATERMARK,
        NA_ERROR_MESSAGE
    )
    VALUES (
        v_log_object_name,
        v_started_at,
        NULL,
        0,
        NULL,
        CONCAT(v_high_watermark, ';lock=pending'),
        NULL
    )
    ON DUPLICATE KEY UPDATE
        DT_LAST_START = VALUES(DT_LAST_START),
        DT_LAST_END = VALUES(DT_LAST_END),
        IS_SUCCESS = VALUES(IS_SUCCESS),
        NU_LAST_ROW_COUNT = VALUES(NU_LAST_ROW_COUNT),
        NA_SOURCE_HIGH_WATERMARK = VALUES(NA_SOURCE_HIGH_WATERMARK),
        NA_ERROR_MESSAGE = VALUES(NA_ERROR_MESSAGE);

    SELECT GET_LOCK('RFFUSION_SUMMARY_REFRESH_LOCK', 0) INTO v_lock_acquired;

    IF COALESCE(v_lock_acquired, 0) = 0 THEN
        SET v_lock_status = 'skipped';
        SET v_finished_at = UTC_TIMESTAMP();

        UPDATE SUMMARY_REFRESH_STATE
        SET
            DT_LAST_END = v_finished_at,
            IS_SUCCESS = 0,
            NU_LAST_ROW_COUNT = NULL,
            NA_SOURCE_HIGH_WATERMARK = CONCAT(v_high_watermark, ';lock=skipped'),
            NA_ERROR_MESSAGE = 'scheduled refresh skipped because a previous run is still active'
        WHERE NA_OBJECT_NAME = CONVERT(v_log_object_name USING utf8mb4) COLLATE utf8mb4_unicode_ci;

        INSERT INTO SUMMARY_REFRESH_LOG (
            NA_OBJECT_NAME,
            DT_STARTED_AT,
            DT_FINISHED_AT,
            IS_SUCCESS,
            NU_ROW_COUNT,
            NA_SOURCE_HIGH_WATERMARK,
            NA_ERROR_MESSAGE
        )
        VALUES (
            v_log_object_name,
            v_started_at,
            v_finished_at,
            0,
            NULL,
            CONCAT(v_high_watermark, ';lock=skipped'),
            'scheduled refresh skipped because a previous run is still active'
        );
    ELSE
        SET v_lock_status = 'acquired';

        CALL PRC_REFRESH_ALL_RFFUSION_SUMMARY_FULL();

        SET v_finished_at = UTC_TIMESTAMP();
        DO RELEASE_LOCK('RFFUSION_SUMMARY_REFRESH_LOCK');

        UPDATE SUMMARY_REFRESH_STATE
        SET
            DT_LAST_END = v_finished_at,
            IS_SUCCESS = 1,
            NU_LAST_ROW_COUNT = 1,
            NA_SOURCE_HIGH_WATERMARK = CONCAT(v_high_watermark, ';lock=acquired'),
            NA_ERROR_MESSAGE = NULL
        WHERE NA_OBJECT_NAME = CONVERT(v_log_object_name USING utf8mb4) COLLATE utf8mb4_unicode_ci;

        INSERT INTO SUMMARY_REFRESH_LOG (
            NA_OBJECT_NAME,
            DT_STARTED_AT,
            DT_FINISHED_AT,
            IS_SUCCESS,
            NU_ROW_COUNT,
            NA_SOURCE_HIGH_WATERMARK,
            NA_ERROR_MESSAGE
        )
        VALUES (
            v_log_object_name,
            v_started_at,
            v_finished_at,
            1,
            1,
            CONCAT(v_high_watermark, ';lock=acquired'),
            NULL
        );
    END IF;
END$$

DELIMITER ;

-- The canonical refresh path is now the Python outbox worker
-- (`appCataloga_rffusion_summary_worker.py`). The heavy MariaDB event is kept
-- out of the bootstrap schema to avoid reintroducing full `INSERT ... SELECT`
-- refreshes on hot operational tables during normal runtime.
