-- Run once before activating the normalized user-directory application.
-- DDL commits independently; legacy tables remain available for recovery.
USE WEBFUSION;

ALTER TABLE `USERS`
  ADD COLUMN IF NOT EXISTS `NA_URL_PROFILE_IMG` varchar(2048) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS `USER_ROLES` (
  `ID_USER` bigint(20) NOT NULL,
  `NA_ROLE` enum('admin','developer') NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT 1,
  `DT_CREATED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  `DT_UPDATED_AT` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID_USER`, `NA_ROLE`),
  KEY `IX_USER_ROLES_ROLE_ACTIVE` (`NA_ROLE`, `IS_ACTIVE`),
  CONSTRAINT `FK_USER_ROLES_USER` FOREIGN KEY (`ID_USER`)
    REFERENCES `USERS` (`ID_USER`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

START TRANSACTION;

-- Preserve existing USERS profiles; import identities found only in legacy roles.
INSERT INTO USERS (
  NA_USER_NAME, NA_USER_EMAIL, NA_JOB_TITLE, NA_DEPARTMENT, NA_LOCATION,
  DT_CREATED_AT, DT_UPDATED_AT
)
SELECT legacy.NA_USER_NAME, legacy.NA_USER_EMAIL, legacy.NA_JOB_TITLE,
       legacy.NA_DEPARTMENT, legacy.NA_LOCATION,
       legacy.DT_CREATED_AT, legacy.DT_UPDATED_AT
FROM ADMINS legacy
WHERE NOT EXISTS (SELECT 1 FROM USERS u WHERE u.NA_USER_EMAIL = legacy.NA_USER_EMAIL);

INSERT INTO USER_ROLES (ID_USER, NA_ROLE, IS_ACTIVE, DT_CREATED_AT, DT_UPDATED_AT)
SELECT u.ID_USER, 'admin', legacy.IS_ACTIVE, legacy.DT_CREATED_AT, legacy.DT_UPDATED_AT
FROM ADMINS legacy JOIN USERS u ON u.NA_USER_EMAIL = legacy.NA_USER_EMAIL
WHERE NOT EXISTS (
  SELECT 1 FROM USER_ROLES r WHERE r.ID_USER = u.ID_USER AND r.NA_ROLE = 'admin'
);

INSERT INTO USERS (
  NA_USER_NAME, NA_USER_EMAIL, NA_JOB_TITLE, NA_DEPARTMENT, NA_LOCATION,
  DT_CREATED_AT, DT_UPDATED_AT
)
SELECT legacy.NA_USER_NAME, legacy.NA_USER_EMAIL, legacy.NA_JOB_TITLE,
       legacy.NA_DEPARTMENT, legacy.NA_LOCATION,
       legacy.DT_CREATED_AT, legacy.DT_UPDATED_AT
FROM DEVELOPERS legacy
WHERE NOT EXISTS (SELECT 1 FROM USERS u WHERE u.NA_USER_EMAIL = legacy.NA_USER_EMAIL);

INSERT INTO USER_ROLES (ID_USER, NA_ROLE, IS_ACTIVE, DT_CREATED_AT, DT_UPDATED_AT)
SELECT u.ID_USER, 'developer', legacy.IS_ACTIVE, legacy.DT_CREATED_AT, legacy.DT_UPDATED_AT
FROM DEVELOPERS legacy JOIN USERS u ON u.NA_USER_EMAIL = legacy.NA_USER_EMAIL
WHERE NOT EXISTS (
  SELECT 1 FROM USER_ROLES r WHERE r.ID_USER = u.ID_USER AND r.NA_ROLE = 'developer'
);

COMMIT;
