-- Add the visit-level read model without changing existing client contracts.
CREATE TABLE IF NOT EXISTS RFFUSION_SUMMARY.HOST_LOCATION_TIMELINE_SUMMARY (
  FK_HOST int(11) NOT NULL,
  NU_VISIT bigint(20) NOT NULL,
  FK_SITE int(11) NOT NULL,
  DT_FIRST_SEEN_AT datetime NOT NULL,
  DT_LAST_SEEN_AT datetime NOT NULL,
  NU_SPECTRUM_COUNT bigint(20) NOT NULL,
  IS_OVERLAPPING tinyint(1) NOT NULL DEFAULT 0,
  DT_REFRESHED_AT datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (FK_HOST, NU_VISIT),
  KEY IX_HOST_TIMELINE_DATE (FK_HOST, DT_FIRST_SEEN_AT),
  KEY IX_HOST_TIMELINE_SITE (FK_SITE, FK_HOST)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
