
USE BPDATA;

-- DELETE FROM `PRC_TASK` WHERE `FK_HOST` IN (10367, 10364, 10567)

UPDATE HOST SET NU_PENDING_PROCESSING = 31, NU_PROCESSING_ERROR = 0 WHERE ID_HOST = 10364;
-- UPDATE PRC_TASK SET BO_ERROR_FLAG = 0 WHERE ID_PRC_TASK = 1

LOAD DATA INFILE '/etc/appCataloga/f2073b.csv'
    INTO TABLE PRC_TASK
    FIELDS TERMINATED BY ';'
    LINES TERMINATED BY '\n' 
    IGNORE 1 LINES
    (FK_HOST, NO_HOST_FILE_PATH, NO_HOST_FILE_NAME, NO_SERVER_FILE_PATH, NO_SERVER_FILE_NAME, DT_PRC_TASK);

-- insert column in PRC_TASK TABLE
ALTER TABLE PRC_TASK ADD COLUMN NA_MESSAGE TEXT COMMENT 'Error message and other information';