
USE BPDATA;

UPDATE HOST SET NU_HOST_FILES = 157, NU_PENDING_BACKUP = 0, NU_BACKUP_ERROR = 0, NU_PENDING_PROCESSING = 157, NU_PROCESSING_ERROR = 0 WHERE ID_HOST = 10597;
UPDATE HOST SET NU_HOST_FILES = 196, NU_PENDING_BACKUP = 0, NU_BACKUP_ERROR = 0, NU_PENDING_PROCESSING = 196, NU_PROCESSING_ERROR = 0 WHERE ID_HOST = 10364;
UPDATE HOST SET NU_HOST_FILES = 1273, NU_PENDING_BACKUP = 0, NU_BACKUP_ERROR = 0, NU_PENDING_PROCESSING = 1273, NU_PROCESSING_ERROR = 0 WHERE ID_HOST = 10367;

LOAD DATA INFILE '/etc/appCataloga/f2073.csv'
    INTO TABLE PRC_TASK
    FIELDS TERMINATED BY ';'
    LINES TERMINATED BY '\n' 
    IGNORE 1 LINES
    (FK_HOST, NO_HOST_FILE_PATH, NO_HOST_FILE_NAME, NO_SERVER_FILE_PATH, NO_SERVER_FILE_NAME, DT_PRC_TASK);

LOAD DATA INFILE '/etc/appCataloga/f2080.csv'
    INTO TABLE PRC_TASK
    FIELDS TERMINATED BY ';'
    LINES TERMINATED BY '\n' 
    IGNORE 1 LINES
    (FK_HOST, NO_HOST_FILE_PATH, NO_HOST_FILE_NAME, NO_SERVER_FILE_PATH, NO_SERVER_FILE_NAME, DT_PRC_TASK);

LOAD DATA INFILE '/etc/appCataloga/f2086.csv'
    INTO TABLE PRC_TASK
    FIELDS TERMINATED BY ';'
    LINES TERMINATED BY '\n' 
    IGNORE 1 LINES
    (FK_HOST, NO_HOST_FILE_PATH, NO_HOST_FILE_NAME, NO_SERVER_FILE_PATH, NO_SERVER_FILE_NAME, DT_PRC_TASK);
